# Supported funding platforms for this project
# Documentation: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-supporter-button-in-your-repository

github: [kodflow]
ko_fi: kodflow
# Additional platforms (uncomment to activate):
# patreon: kodflow
# open_collective: kodflow
# liberapay: kodflow
# buy_me_a_coffee: kodflow
# custom: ['https://paypal.me/kodflow']
