# These are supported funding model platforms

github: [kodflow]
# patreon: kodflow
# open_collective: kodflow
# ko_fi: kodflow
# tidelift: npm/terraform-provider-n8n
# community_bridge: terraform-provider-n8n
# liberapay: kodflow
# issuehunt: kodflow
# lfx_crowdfunding: terraform-provider-n8n
# polar: kodflow
# buy_me_a_coffee: kodflow
# thanks_dev: kodflow
# custom: ['https://paypal.me/kodflow', 'https://donate.example.com']
