# CodeRabbit Configuration for Terraform Provider n8n
# Documentation: https://docs.coderabbit.ai/guides/configure-coderabbit

language: en-US
early_access: true
enable_free_tier: true

reviews:
  # Automatically review PRs
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - develop

  # Profile configuration for specific review focus
  profile: chill

  # Request changes workflow
  request_changes_workflow: false

  # High level summary
  high_level_summary: true

  # Poem style summary
  poem: false

  # Review status
  review_status: true

  # Collapse walkthrough
  collapse_walkthrough: false

  # Auto-reply to comments
  auto_reply: true

  # Path-specific instructions
  path_instructions:
    - path: "src/**/*.go"
      instructions: |
        - Follow Go best practices and idioms
        - Ensure proper error handling
        - Check for goroutine leaks
        - Verify context usage
        - Check for proper resource cleanup (defer statements)
        - Ensure Terraform Plugin Framework conventions are followed
        - Validate schema definitions and type safety

    - path: "src/**/BUILD.bazel"
      instructions: |
        - Verify Bazel targets are correctly defined
        - Check dependencies are properly declared
        - Ensure visibility rules are appropriate
        - Validate test targets have proper data dependencies

    - path: "**/*.tf"
      instructions: |
        - Check Terraform syntax and best practices
        - Verify variable types and descriptions
        - Ensure outputs are documented
        - Check for sensitive data handling

    - path: ".github/workflows/*.yml"
      instructions: |
        - Verify GitHub Actions syntax
        - Check for secrets usage and security
        - Ensure jobs have proper dependencies
        - Validate caching strategies
        - Check for conventional commits validation

    - path: "MODULE.bazel"
      instructions: |
        - Verify bzlmod dependency declarations
        - Check for version compatibility (Bazel 9+)
        - Ensure Go toolchain version (1.24+)
        - Validate rules_go and gazelle versions

chat:
  # Enable chat functionality
  auto_reply: true

# Tools configuration
tools:
  # Ruff for Python (if any)
  ruff:
    enabled: false

  # Shellcheck for shell scripts
  shellcheck:
    enabled: true

  # Gitleaks for secret detection
  gitleaks:
    enabled: true

  # Hadolint for Dockerfile
  hadolint:
    enabled: true

  # Yamllint for YAML files
  yamllint:
    enabled: true

  # Markdownlint for Markdown
  markdownlint:
    enabled: true

  # Golangci-lint for Go code
  golangci-lint:
    enabled: true

  # Actionlint for GitHub Actions
  actionlint:
    enabled: true

# Issue labels to apply
labels:
  - "coderabbit"

# Abort review on certain file patterns
abort_on_close: true

# Knowledge base settings
knowledge_base:
  enabled: true
  learnings:
    - "This is a Terraform Provider built with Terraform Plugin Framework (not SDK)"
    - "Uses Bazel 9 with bzlmod for dependency management"
    - "Go version must be 1.24+ for compatibility with terraform-plugin-framework v1.16+"
    - "Follows Conventional Commits for semantic versioning"
    - "All documentation must be in English"
    - "Provider targets n8n API for workflow automation management"
    - "Tests must be hermetic and reproducible with Bazel"
    - "Breaking changes require major version bump (use ! or BREAKING CHANGE)"

# Review filters
reviews_filters:
  # Files to exclude from review
  exclude_patterns:
    - "**/*.pb.go"
    - "**/*.gen.go"
    - "**/vendor/**"
    - "bazel-*/**"
    - "**/*.sum"
    - ".bazelrc"
    - ".bazelversion"
    - "CHANGELOG.md"
    - "**/node_modules/**"
    - "**/*.md" # Only exclude basic markdown review, still check with markdownlint
    - "**/*.lock"

  # File size limits (in KB)
  max_file_size: 500

# Code conventions
conventions:
  - "Use conventional commits format: <type>(<scope>): <description>"
  - "PR titles must follow conventional commits"
  - "Breaking changes must be clearly marked with ! or BREAKING CHANGE"
  - "All public Go functions must have godoc comments"
  - "Error messages should be lowercase and not end with punctuation"
  - "Use consistent naming: provider resources should be prefixed with 'n8n_'"
  - "Tests should follow table-driven test pattern where applicable"
  - "All Terraform configurations must include examples in comments"

# Custom prompts
prompts:
  review:
    - "Check for proper error handling in Go code"
    - "Verify Terraform schema definitions are correct"
    - "Ensure tests are comprehensive and follow Bazel best practices"
    - "Check that changes maintain backward compatibility unless marked as breaking"
    - "Verify conventional commit format in PR title"
    - "Check for potential security issues (secrets, API keys)"
    - "Ensure all exported functions and types have documentation"
    - "Verify Bazel build files are correctly structured"
