# Copyright (c) 2024 Florent (Kodflow). All rights reserved.
# Licensed under the Sustainable Use License 1.0
# See LICENSE.md in the project root for license information.

---
# Codacy configuration file
# https://docs.codacy.com/repositories-configure/codacy-configuration-file/

# Exclude patterns - files that should not be analyzed
exclude_paths:
  # DevContainer generated files with secrets
  - ".devcontainer/mcp.json"

  # Generated SDK and Bazel files
  - "sdk/n8nsdk/**"
  - "bazel-*/**"
  - "**/BUILD.bazel"
  - "**/*.pb.go"

  # Test files (exclude from quality issues, keep for coverage)
  - "**/*_test.go"

  # Standard exclusions
  - "node_modules/**"
  - "vendor/**"
  - "dist/**"
  - "build/**"
  - "*.min.js"
  - "*.min.css"
  - ".terraform/**"
  - "*.tfstate"
  - "*.tfstate.backup"
