# Copyright (c) 2024 Florent (Kodflow). All rights reserved.
# Licensed under the Sustainable Use License 1.0
# See LICENSE.md in the project root for license information.

---
# Codacy configuration file
# https://docs.codacy.com/repositories-configure/codacy-configuration-file/

# Exclude patterns - files that should not be analyzed
exclude_paths:
  # DevContainer generated files with secrets
  - ".devcontainer/mcp.json"

  # Standard exclusions
  - "node_modules/**"
  - "vendor/**"
  - "dist/**"
  - "build/**"
  - "*.min.js"
  - "*.min.css"

# Engines configuration
engines:
  trivy:
    exclude_paths:
      - ".devcontainer/mcp.json"
