# Copyright (c) 2024 Florent (Kodflow). All rights reserved.
# Licensed under the Sustainable Use License 1.0
# See LICENSE.md in the project root for license information.

---
# Codacy configuration
# https://docs.codacy.com/repositories-configure/codacy-configuration-file/

# Exclude generated and third-party files from analysis
exclude_paths:
  # Terraform plugin generated documentation
  - "docs/**"
  # Bazel build artifacts
  - "bazel-*/**"
  # Third-party dependencies
  - "vendor/**"
  - "third_party/**"
  # Generated SDK
  - "sdk/**"
