# golangci-lint configuration for Terraform Provider n8n
# Documentation: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  go: "1.24"
  modules-download-mode: readonly

linters:
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters
    # - revive  # Disabled: conflicts with ktn-linter requirements
    - gosec
    - misspell
    - unconvert
    - unparam
    - goconst
    - gocyclo
    - gocognit
    - godot
    - gocritic
    - bodyclose
    - noctx
    - errname
    - errorlint
    - gomodguard
    - goprintffuncname
    - predeclared
    - thelper
    - wastedassign

linters-settings:
  # custom:
  #   ktn-linter:
  #     path: /home/vscode/.local/bin/ktn-linter
  #     description: Strict Go linter enforcing code quality standards
  #     original-url: github.com/kodflow/ktn-linter
  #     command: ktn-linter
  #     args:
  #       - lint
  #       - --simple
  #       - ./...
  #     pattern: '^(?P<path>[^\s]+):(?P<line>\d+):(?P<column>\d+):\s+(?P<message>.+)$'

  errcheck:
    check-type-assertions: true
    check-blank: true

  gosec:
    excludes:
      - G104
      - G306

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - whyNoLint
      - unnamedResult

  staticcheck:
    checks: ["all"]

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-dirs:
    - vendor
    - testdata
    - bazel-*

  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - goconst
        - unparam
        - gocognit

    - path: internal/provider/
      linters:
        - gocritic

    - path: ".*\\.pb\\.go$"
      linters:
        - all

    - path: "mock_.*\\.go$"
      linters:
        - all
