# ktn-linter configuration for n8n Terraform Provider
# Documentation: https://github.com/kodflow/ktn-linter

# Disable rules that conflict with Terraform provider patterns
disabled-rules:
  # Terraform providers have specific patterns that don't always match ktn-linter expectations
  - KTN-FUNC-007 # Params/Returns sections - Terraform uses different doc style
  - KTN-FUNC-011 # Comment on every if/return - too verbose for Terraform CRUD
  - KTN-VAR-001 # Explicit types - Terraform SDK uses type inference
  - KTN-VAR-002 # Variable grouping - Terraform resources have complex structures
  - KTN-VAR-004 # Comment on variables - covered by struct field docs
  - KTN-TEST-002 # Test file without source - acceptable for integration tests

# Paths to exclude from linting
exclude-paths:
  - "sdk/**" # Generated SDK code
  - "bazel-*/**" # Bazel build artifacts
  - "vendor/**" # Vendored dependencies
  - "**/*_test.go" # Test files (have different rules)
  - "examples/**" # Example code
  - "codegen/**" # Code generation scripts

# Keep enabled rules that are valuable for Terraform providers
enabled-rules:
  - KTN-FUNC-001 # Function documentation
  - KTN-FUNC-002 # Function complexity
  - KTN-STRUCT-001 # Struct documentation
  - KTN-ERROR-001 # Error handling
  - KTN-ERROR-002 # Error wrapping
