# Copyright (c) 2024 Florent (Kodflow). All rights reserved.
# Licensed under the Sustainable Use License 1.0
# See LICENSE.md in the project root for license information.

branches:
  - main

plugins:
  # Analyser les commits conventionnels et déterminer la version
  - - "@semantic-release/commit-analyzer"
    - preset: "conventionalcommits"
      releaseRules:
        - type: "feat"
          release: "minor"
        - type: "fix"
          release: "patch"
        - type: "perf"
          release: "patch"
        - type: "refactor"
          release: "patch"
        - type: "docs"
          release: false
        - type: "test"
          release: false
        - type: "chore"
          release: false
        - type: "ci"
          release: false
        - type: "build"
          release: "patch"
        - scope: "breaking"
          release: "major"

  # Générer les release notes
  - - "@semantic-release/release-notes-generator"
    - preset: "conventionalcommits"
      presetConfig:
        types:
          - type: "feat"
            section: "🚀 Features"
          - type: "fix"
            section: "🐛 Bug Fixes"
          - type: "perf"
            section: "⚡ Performance"
          - type: "refactor"
            section: "♻️ Refactoring"
          - type: "build"
            section: "🔧 Build"
          - type: "docs"
            section: "📚 Documentation"
          - type: "test"
            section: "✅ Tests"
          - type: "chore"
            section: "🧹 Chores"
          - type: "ci"
            section: "👷 CI/CD"

  # NOTE: Changelog generation disabled - will be done in PRs
  # No commits on main after PR merge - keeps history clean
  # Tags are created by semantic-release and trigger GoReleaser

  # Créer la release GitHub avec les notes
  # NOTE: Disabled - GoReleaser creates the release with compiled binaries
  # - - "@semantic-release/github"
  #   - successComment: false
  #     failComment: false
  #     releasedLabels: false
  #     assets: []

  # Trigger GoReleaser workflow by pushing the tag
  - - "@semantic-release/exec"
    - publishCmd: |
        echo "Tag ${nextRelease.version} will trigger GoReleaser workflow"
        echo "Release will be created by .github/workflows/release.yml"

# Options globales
tagFormat: "v${version}"
