/*
n8n Public API

Testing SourceControlAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package n8nsdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/kodflow/n8n/sdk/n8nsdk"
)

func Test_n8nsdk_SourceControlAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SourceControlAPIService SourceControlPullPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SourceControlAPI.SourceControlPullPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
