/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

type ProjectsAPI interface {

	/*
		ProjectsGet Retrieve projects

		Retrieve projects from your instance.

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return ProjectsAPIProjectsGetRequest
	*/
	ProjectsGet(ctx context.Context) ProjectsAPIProjectsGetRequest

	// ProjectsGetExecute executes the request
	//  @return ProjectList
	ProjectsGetExecute(r ProjectsAPIProjectsGetRequest) (*ProjectList, *http.Response, error)

	/*
		ProjectsPost Create a project

		Create a project on your instance.

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return ProjectsAPIProjectsPostRequest
	*/
	ProjectsPost(ctx context.Context) ProjectsAPIProjectsPostRequest

	// ProjectsPostExecute executes the request
	ProjectsPostExecute(r ProjectsAPIProjectsPostRequest) (*http.Response, error)

	/*
		ProjectsProjectIdDelete Delete a project

		Delete a project from your instance.

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param projectId The ID of the project.
		@return ProjectsAPIProjectsProjectIdDeleteRequest
	*/
	ProjectsProjectIdDelete(ctx context.Context, projectId string) ProjectsAPIProjectsProjectIdDeleteRequest

	// ProjectsProjectIdDeleteExecute executes the request
	ProjectsProjectIdDeleteExecute(r ProjectsAPIProjectsProjectIdDeleteRequest) (*http.Response, error)

	/*
		ProjectsProjectIdPut Update a project

		Update a project on your instance.

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param projectId The ID of the project.
		@return ProjectsAPIProjectsProjectIdPutRequest
	*/
	ProjectsProjectIdPut(ctx context.Context, projectId string) ProjectsAPIProjectsProjectIdPutRequest

	// ProjectsProjectIdPutExecute executes the request
	ProjectsProjectIdPutExecute(r ProjectsAPIProjectsProjectIdPutRequest) (*http.Response, error)

	/*
		ProjectsProjectIdUsersPost Add one or more users to a project

		Add one or more users to a project on your instance.

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param projectId The ID of the project.
		@return ProjectsAPIProjectsProjectIdUsersPostRequest
	*/
	ProjectsProjectIdUsersPost(ctx context.Context, projectId string) ProjectsAPIProjectsProjectIdUsersPostRequest

	// ProjectsProjectIdUsersPostExecute executes the request
	ProjectsProjectIdUsersPostExecute(r ProjectsAPIProjectsProjectIdUsersPostRequest) (*http.Response, error)

	/*
		ProjectsProjectIdUsersUserIdDelete Delete a user from a project

		Delete a user from a project on your instance.

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param projectId The ID of the project.
		@param userId The ID of the user.
		@return ProjectsAPIProjectsProjectIdUsersUserIdDeleteRequest
	*/
	ProjectsProjectIdUsersUserIdDelete(ctx context.Context, projectId string, userId string) ProjectsAPIProjectsProjectIdUsersUserIdDeleteRequest

	// ProjectsProjectIdUsersUserIdDeleteExecute executes the request
	ProjectsProjectIdUsersUserIdDeleteExecute(r ProjectsAPIProjectsProjectIdUsersUserIdDeleteRequest) (*http.Response, error)

	/*
		ProjectsProjectIdUsersUserIdPatch Change a user's role in a project

		Change a user's role in a project.

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param projectId The ID of the project.
		@param userId The ID of the user.
		@return ProjectsAPIProjectsProjectIdUsersUserIdPatchRequest
	*/
	ProjectsProjectIdUsersUserIdPatch(ctx context.Context, projectId string, userId string) ProjectsAPIProjectsProjectIdUsersUserIdPatchRequest

	// ProjectsProjectIdUsersUserIdPatchExecute executes the request
	ProjectsProjectIdUsersUserIdPatchExecute(r ProjectsAPIProjectsProjectIdUsersUserIdPatchRequest) (*http.Response, error)
}

// ProjectsAPIService ProjectsAPI service
type ProjectsAPIService service

type ProjectsAPIProjectsGetRequest struct {
	ctx        context.Context
	ApiService ProjectsAPI
	limit      *float32
	cursor     *string
}

// The maximum number of items to return.
func (r ProjectsAPIProjectsGetRequest) Limit(limit float32) ProjectsAPIProjectsGetRequest {
	r.limit = &limit
	return r
}

// Paginate by setting the cursor parameter to the nextCursor attribute returned by the previous request&#39;s response. Default value fetches the first \&quot;page\&quot; of the collection. See pagination for more detail.
func (r ProjectsAPIProjectsGetRequest) Cursor(cursor string) ProjectsAPIProjectsGetRequest {
	r.cursor = &cursor
	return r
}

func (r ProjectsAPIProjectsGetRequest) Execute() (*ProjectList, *http.Response, error) {
	return r.ApiService.ProjectsGetExecute(r)
}

/*
ProjectsGet Retrieve projects

Retrieve projects from your instance.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ProjectsAPIProjectsGetRequest
*/
func (a *ProjectsAPIService) ProjectsGet(ctx context.Context) ProjectsAPIProjectsGetRequest {
	return ProjectsAPIProjectsGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ProjectList
func (a *ProjectsAPIService) ProjectsGetExecute(r ProjectsAPIProjectsGetRequest) (*ProjectList, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ProjectList
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ProjectsAPIService.ProjectsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/projects"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	} else {
		var defaultValue float32 = 100
		r.limit = &defaultValue
	}
	if r.cursor != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "cursor", r.cursor, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-N8N-API-KEY"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ProjectsAPIProjectsPostRequest struct {
	ctx        context.Context
	ApiService ProjectsAPI
	project    *Project
}

// Payload for project to create.
func (r ProjectsAPIProjectsPostRequest) Project(project Project) ProjectsAPIProjectsPostRequest {
	r.project = &project
	return r
}

func (r ProjectsAPIProjectsPostRequest) Execute() (*http.Response, error) {
	return r.ApiService.ProjectsPostExecute(r)
}

/*
ProjectsPost Create a project

Create a project on your instance.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ProjectsAPIProjectsPostRequest
*/
func (a *ProjectsAPIService) ProjectsPost(ctx context.Context) ProjectsAPIProjectsPostRequest {
	return ProjectsAPIProjectsPostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
func (a *ProjectsAPIService) ProjectsPostExecute(r ProjectsAPIProjectsPostRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodPost
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ProjectsAPIService.ProjectsPost")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/projects"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.project == nil {
		return nil, reportError("project is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.project
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-N8N-API-KEY"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ProjectsAPIProjectsProjectIdDeleteRequest struct {
	ctx        context.Context
	ApiService ProjectsAPI
	projectId  string
}

func (r ProjectsAPIProjectsProjectIdDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.ProjectsProjectIdDeleteExecute(r)
}

/*
ProjectsProjectIdDelete Delete a project

Delete a project from your instance.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param projectId The ID of the project.
	@return ProjectsAPIProjectsProjectIdDeleteRequest
*/
func (a *ProjectsAPIService) ProjectsProjectIdDelete(ctx context.Context, projectId string) ProjectsAPIProjectsProjectIdDeleteRequest {
	return ProjectsAPIProjectsProjectIdDeleteRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
	}
}

// Execute executes the request
func (a *ProjectsAPIService) ProjectsProjectIdDeleteExecute(r ProjectsAPIProjectsProjectIdDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ProjectsAPIService.ProjectsProjectIdDelete")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/projects/{projectId}"
	localVarPath = strings.Replace(localVarPath, "{"+"projectId"+"}", url.PathEscape(parameterValueToString(r.projectId, "projectId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-N8N-API-KEY"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ProjectsAPIProjectsProjectIdPutRequest struct {
	ctx        context.Context
	ApiService ProjectsAPI
	projectId  string
	project    *Project
}

// Updated project object.
func (r ProjectsAPIProjectsProjectIdPutRequest) Project(project Project) ProjectsAPIProjectsProjectIdPutRequest {
	r.project = &project
	return r
}

func (r ProjectsAPIProjectsProjectIdPutRequest) Execute() (*http.Response, error) {
	return r.ApiService.ProjectsProjectIdPutExecute(r)
}

/*
ProjectsProjectIdPut Update a project

Update a project on your instance.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param projectId The ID of the project.
	@return ProjectsAPIProjectsProjectIdPutRequest
*/
func (a *ProjectsAPIService) ProjectsProjectIdPut(ctx context.Context, projectId string) ProjectsAPIProjectsProjectIdPutRequest {
	return ProjectsAPIProjectsProjectIdPutRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
	}
}

// Execute executes the request
func (a *ProjectsAPIService) ProjectsProjectIdPutExecute(r ProjectsAPIProjectsProjectIdPutRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodPut
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ProjectsAPIService.ProjectsProjectIdPut")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/projects/{projectId}"
	localVarPath = strings.Replace(localVarPath, "{"+"projectId"+"}", url.PathEscape(parameterValueToString(r.projectId, "projectId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.project == nil {
		return nil, reportError("project is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.project
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-N8N-API-KEY"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ProjectsAPIProjectsProjectIdUsersPostRequest struct {
	ctx                               context.Context
	ApiService                        ProjectsAPI
	projectId                         string
	projectsProjectIdUsersPostRequest *ProjectsProjectIdUsersPostRequest
}

// Payload containing an array of one or more users to add to the project.
func (r ProjectsAPIProjectsProjectIdUsersPostRequest) ProjectsProjectIdUsersPostRequest(projectsProjectIdUsersPostRequest ProjectsProjectIdUsersPostRequest) ProjectsAPIProjectsProjectIdUsersPostRequest {
	r.projectsProjectIdUsersPostRequest = &projectsProjectIdUsersPostRequest
	return r
}

func (r ProjectsAPIProjectsProjectIdUsersPostRequest) Execute() (*http.Response, error) {
	return r.ApiService.ProjectsProjectIdUsersPostExecute(r)
}

/*
ProjectsProjectIdUsersPost Add one or more users to a project

Add one or more users to a project on your instance.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param projectId The ID of the project.
	@return ProjectsAPIProjectsProjectIdUsersPostRequest
*/
func (a *ProjectsAPIService) ProjectsProjectIdUsersPost(ctx context.Context, projectId string) ProjectsAPIProjectsProjectIdUsersPostRequest {
	return ProjectsAPIProjectsProjectIdUsersPostRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
	}
}

// Execute executes the request
func (a *ProjectsAPIService) ProjectsProjectIdUsersPostExecute(r ProjectsAPIProjectsProjectIdUsersPostRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodPost
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ProjectsAPIService.ProjectsProjectIdUsersPost")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/projects/{projectId}/users"
	localVarPath = strings.Replace(localVarPath, "{"+"projectId"+"}", url.PathEscape(parameterValueToString(r.projectId, "projectId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.projectsProjectIdUsersPostRequest
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-N8N-API-KEY"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ProjectsAPIProjectsProjectIdUsersUserIdDeleteRequest struct {
	ctx        context.Context
	ApiService ProjectsAPI
	projectId  string
	userId     string
}

func (r ProjectsAPIProjectsProjectIdUsersUserIdDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.ProjectsProjectIdUsersUserIdDeleteExecute(r)
}

/*
ProjectsProjectIdUsersUserIdDelete Delete a user from a project

Delete a user from a project on your instance.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param projectId The ID of the project.
	@param userId The ID of the user.
	@return ProjectsAPIProjectsProjectIdUsersUserIdDeleteRequest
*/
func (a *ProjectsAPIService) ProjectsProjectIdUsersUserIdDelete(ctx context.Context, projectId string, userId string) ProjectsAPIProjectsProjectIdUsersUserIdDeleteRequest {
	return ProjectsAPIProjectsProjectIdUsersUserIdDeleteRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
		userId:     userId,
	}
}

// Execute executes the request
func (a *ProjectsAPIService) ProjectsProjectIdUsersUserIdDeleteExecute(r ProjectsAPIProjectsProjectIdUsersUserIdDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ProjectsAPIService.ProjectsProjectIdUsersUserIdDelete")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/projects/{projectId}/users/{userId}"
	localVarPath = strings.Replace(localVarPath, "{"+"projectId"+"}", url.PathEscape(parameterValueToString(r.projectId, "projectId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"userId"+"}", url.PathEscape(parameterValueToString(r.userId, "userId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-N8N-API-KEY"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ProjectsAPIProjectsProjectIdUsersUserIdPatchRequest struct {
	ctx                                      context.Context
	ApiService                               ProjectsAPI
	projectId                                string
	userId                                   string
	projectsProjectIdUsersUserIdPatchRequest *ProjectsProjectIdUsersUserIdPatchRequest
}

// Payload containing the new role to assign to the project user.
func (r ProjectsAPIProjectsProjectIdUsersUserIdPatchRequest) ProjectsProjectIdUsersUserIdPatchRequest(projectsProjectIdUsersUserIdPatchRequest ProjectsProjectIdUsersUserIdPatchRequest) ProjectsAPIProjectsProjectIdUsersUserIdPatchRequest {
	r.projectsProjectIdUsersUserIdPatchRequest = &projectsProjectIdUsersUserIdPatchRequest
	return r
}

func (r ProjectsAPIProjectsProjectIdUsersUserIdPatchRequest) Execute() (*http.Response, error) {
	return r.ApiService.ProjectsProjectIdUsersUserIdPatchExecute(r)
}

/*
ProjectsProjectIdUsersUserIdPatch Change a user's role in a project

Change a user's role in a project.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param projectId The ID of the project.
	@param userId The ID of the user.
	@return ProjectsAPIProjectsProjectIdUsersUserIdPatchRequest
*/
func (a *ProjectsAPIService) ProjectsProjectIdUsersUserIdPatch(ctx context.Context, projectId string, userId string) ProjectsAPIProjectsProjectIdUsersUserIdPatchRequest {
	return ProjectsAPIProjectsProjectIdUsersUserIdPatchRequest{
		ApiService: a,
		ctx:        ctx,
		projectId:  projectId,
		userId:     userId,
	}
}

// Execute executes the request
func (a *ProjectsAPIService) ProjectsProjectIdUsersUserIdPatchExecute(r ProjectsAPIProjectsProjectIdUsersUserIdPatchRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodPatch
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ProjectsAPIService.ProjectsProjectIdUsersUserIdPatch")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/projects/{projectId}/users/{userId}"
	localVarPath = strings.Replace(localVarPath, "{"+"projectId"+"}", url.PathEscape(parameterValueToString(r.projectId, "projectId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"userId"+"}", url.PathEscape(parameterValueToString(r.userId, "userId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.projectsProjectIdUsersUserIdPatchRequest
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-N8N-API-KEY"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
