/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
)

// checks if the ExecutionList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExecutionList{}

// ExecutionList struct for ExecutionList
type ExecutionList struct {
	Data []Execution `json:"data,omitempty"`
	// Paginate through executions by setting the cursor parameter to a nextCursor attribute returned by a previous request. Default value fetches the first \"page\" of the collection.
	NextCursor NullableString `json:"nextCursor,omitempty"`
}

// NewExecutionList instantiates a new ExecutionList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExecutionList() *ExecutionList {
	this := ExecutionList{}
	return &this
}

// NewExecutionListWithDefaults instantiates a new ExecutionList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExecutionListWithDefaults() *ExecutionList {
	this := ExecutionList{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ExecutionList) GetData() []Execution {
	if o == nil || IsNil(o.Data) {
		var ret []Execution
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExecutionList) GetDataOk() ([]Execution, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ExecutionList) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Execution and assigns it to the Data field.
func (o *ExecutionList) SetData(v []Execution) {
	o.Data = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExecutionList) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor.Get()) {
		var ret string
		return ret
	}
	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExecutionList) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// HasNextCursor returns a boolean if a field has been set.
func (o *ExecutionList) HasNextCursor() bool {
	if o != nil && o.NextCursor.IsSet() {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given NullableString and assigns it to the NextCursor field.
func (o *ExecutionList) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}
// SetNextCursorNil sets the value for NextCursor to be an explicit nil
func (o *ExecutionList) SetNextCursorNil() {
	o.NextCursor.Set(nil)
}

// UnsetNextCursor ensures that no value is present for NextCursor, not even an explicit nil
func (o *ExecutionList) UnsetNextCursor() {
	o.NextCursor.Unset()
}

func (o ExecutionList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExecutionList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if o.NextCursor.IsSet() {
		toSerialize["nextCursor"] = o.NextCursor.Get()
	}
	return toSerialize, nil
}

type NullableExecutionList struct {
	value *ExecutionList
	isSet bool
}

func (v NullableExecutionList) Get() *ExecutionList {
	return v.value
}

func (v *NullableExecutionList) Set(val *ExecutionList) {
	v.value = val
	v.isSet = true
}

func (v NullableExecutionList) IsSet() bool {
	return v.isSet
}

func (v *NullableExecutionList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecutionList(val *ExecutionList) *NullableExecutionList {
	return &NullableExecutionList{value: val, isSet: true}
}

func (v NullableExecutionList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecutionList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


