/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the CredentialSharedItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CredentialSharedItem{}

// CredentialSharedItem struct for CredentialSharedItem
type CredentialSharedItem struct {
	// Project ID
	Id string `json:"id"`
	// Project name
	Name string `json:"name"`
	// Role of the credential in this project (e.g. credential:owner)
	Role string `json:"role"`
	// When the credential was shared with this project
	CreatedAt time.Time `json:"createdAt"`
	// When the sharing was last updated
	UpdatedAt            time.Time `json:"updatedAt"`
	AdditionalProperties map[string]interface{}
}

type _CredentialSharedItem CredentialSharedItem

// NewCredentialSharedItem instantiates a new CredentialSharedItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialSharedItem(id string, name string, role string, createdAt time.Time, updatedAt time.Time) *CredentialSharedItem {
	this := CredentialSharedItem{}
	this.Id = id
	this.Name = name
	this.Role = role
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewCredentialSharedItemWithDefaults instantiates a new CredentialSharedItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialSharedItemWithDefaults() *CredentialSharedItem {
	this := CredentialSharedItem{}
	return &this
}

// GetId returns the Id field value
func (o *CredentialSharedItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CredentialSharedItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CredentialSharedItem) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *CredentialSharedItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CredentialSharedItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CredentialSharedItem) SetName(v string) {
	o.Name = v
}

// GetRole returns the Role field value
func (o *CredentialSharedItem) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *CredentialSharedItem) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *CredentialSharedItem) SetRole(v string) {
	o.Role = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CredentialSharedItem) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CredentialSharedItem) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CredentialSharedItem) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *CredentialSharedItem) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *CredentialSharedItem) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *CredentialSharedItem) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o CredentialSharedItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CredentialSharedItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["role"] = o.Role
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CredentialSharedItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"role",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCredentialSharedItem := _CredentialSharedItem{}

	err = json.Unmarshal(data, &varCredentialSharedItem)

	if err != nil {
		return err
	}

	*o = CredentialSharedItem(varCredentialSharedItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "role")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCredentialSharedItem struct {
	value *CredentialSharedItem
	isSet bool
}

func (v NullableCredentialSharedItem) Get() *CredentialSharedItem {
	return v.value
}

func (v *NullableCredentialSharedItem) Set(val *CredentialSharedItem) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialSharedItem) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialSharedItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialSharedItem(val *CredentialSharedItem) *NullableCredentialSharedItem {
	return &NullableCredentialSharedItem{value: val, isSet: true}
}

func (v NullableCredentialSharedItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialSharedItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
