/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateDataTableRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDataTableRequest{}

// UpdateDataTableRequest struct for UpdateDataTableRequest
type UpdateDataTableRequest struct {
	// New name for the data table
	Name                 string `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _UpdateDataTableRequest UpdateDataTableRequest

// NewUpdateDataTableRequest instantiates a new UpdateDataTableRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDataTableRequest(name string) *UpdateDataTableRequest {
	this := UpdateDataTableRequest{}
	this.Name = name
	return &this
}

// NewUpdateDataTableRequestWithDefaults instantiates a new UpdateDataTableRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDataTableRequestWithDefaults() *UpdateDataTableRequest {
	this := UpdateDataTableRequest{}
	return &this
}

// GetName returns the Name field value
func (o *UpdateDataTableRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateDataTableRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateDataTableRequest) SetName(v string) {
	o.Name = v
}

func (o UpdateDataTableRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDataTableRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateDataTableRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateDataTableRequest := _UpdateDataTableRequest{}

	err = json.Unmarshal(data, &varUpdateDataTableRequest)

	if err != nil {
		return err
	}

	*o = UpdateDataTableRequest(varUpdateDataTableRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateDataTableRequest struct {
	value *UpdateDataTableRequest
	isSet bool
}

func (v NullableUpdateDataTableRequest) Get() *UpdateDataTableRequest {
	return v.value
}

func (v *NullableUpdateDataTableRequest) Set(val *UpdateDataTableRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDataTableRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDataTableRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDataTableRequest(val *UpdateDataTableRequest) *NullableUpdateDataTableRequest {
	return &NullableUpdateDataTableRequest{value: val, isSet: true}
}

func (v NullableUpdateDataTableRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDataTableRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
