/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
)

// checks if the WorkflowsIdActivatePostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowsIdActivatePostRequest{}

// WorkflowsIdActivatePostRequest struct for WorkflowsIdActivatePostRequest
type WorkflowsIdActivatePostRequest struct {
	// The specific version ID to activate or publish. If not provided, the latest version is used.
	VersionId *string `json:"versionId,omitempty"`
	// Optional name for the workflow version during activation.
	Name *string `json:"name,omitempty"`
	// Optional description for the workflow version during activation.
	Description          *string `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WorkflowsIdActivatePostRequest WorkflowsIdActivatePostRequest

// NewWorkflowsIdActivatePostRequest instantiates a new WorkflowsIdActivatePostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowsIdActivatePostRequest() *WorkflowsIdActivatePostRequest {
	this := WorkflowsIdActivatePostRequest{}
	return &this
}

// NewWorkflowsIdActivatePostRequestWithDefaults instantiates a new WorkflowsIdActivatePostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowsIdActivatePostRequestWithDefaults() *WorkflowsIdActivatePostRequest {
	this := WorkflowsIdActivatePostRequest{}
	return &this
}

// GetVersionId returns the VersionId field value if set, zero value otherwise.
func (o *WorkflowsIdActivatePostRequest) GetVersionId() string {
	if o == nil || IsNil(o.VersionId) {
		var ret string
		return ret
	}
	return *o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowsIdActivatePostRequest) GetVersionIdOk() (*string, bool) {
	if o == nil || IsNil(o.VersionId) {
		return nil, false
	}
	return o.VersionId, true
}

// HasVersionId returns a boolean if a field has been set.
func (o *WorkflowsIdActivatePostRequest) HasVersionId() bool {
	if o != nil && !IsNil(o.VersionId) {
		return true
	}

	return false
}

// SetVersionId gets a reference to the given string and assigns it to the VersionId field.
func (o *WorkflowsIdActivatePostRequest) SetVersionId(v string) {
	o.VersionId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *WorkflowsIdActivatePostRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowsIdActivatePostRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *WorkflowsIdActivatePostRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *WorkflowsIdActivatePostRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *WorkflowsIdActivatePostRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowsIdActivatePostRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *WorkflowsIdActivatePostRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *WorkflowsIdActivatePostRequest) SetDescription(v string) {
	o.Description = &v
}

func (o WorkflowsIdActivatePostRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowsIdActivatePostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VersionId) {
		toSerialize["versionId"] = o.VersionId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WorkflowsIdActivatePostRequest) UnmarshalJSON(data []byte) (err error) {
	varWorkflowsIdActivatePostRequest := _WorkflowsIdActivatePostRequest{}

	err = json.Unmarshal(data, &varWorkflowsIdActivatePostRequest)

	if err != nil {
		return err
	}

	*o = WorkflowsIdActivatePostRequest(varWorkflowsIdActivatePostRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "versionId")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWorkflowsIdActivatePostRequest struct {
	value *WorkflowsIdActivatePostRequest
	isSet bool
}

func (v NullableWorkflowsIdActivatePostRequest) Get() *WorkflowsIdActivatePostRequest {
	return v.value
}

func (v *NullableWorkflowsIdActivatePostRequest) Set(val *WorkflowsIdActivatePostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowsIdActivatePostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowsIdActivatePostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowsIdActivatePostRequest(val *WorkflowsIdActivatePostRequest) *NullableWorkflowsIdActivatePostRequest {
	return &NullableWorkflowsIdActivatePostRequest{value: val, isSet: true}
}

func (v NullableWorkflowsIdActivatePostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowsIdActivatePostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
