/*
n8n Public API

n8n Public API

API version: 2.0.0
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"time"
)

// ProjectMember represents a user with their role in a project.
type ProjectMember struct {
	// The user's unique identifier.
	ID *string `json:"id,omitempty"`
	// The user's email address.
	Email *string `json:"email,omitempty"`
	// The user's first name.
	FirstName *string `json:"firstName,omitempty"`
	// The user's last name.
	LastName *string `json:"lastName,omitempty"`
	// The user's role in the project (e.g. project:admin, project:viewer).
	Role *string `json:"role,omitempty"`
	// When the user was created.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// When the user was last updated.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// ProjectMemberList is the response for listing project members.
type ProjectMemberList struct {
	// List of project members.
	Data []ProjectMember `json:"data,omitempty"`
	// Cursor for pagination.
	NextCursor *string `json:"nextCursor,omitempty"`
}
