/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsersIdRolePatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersIdRolePatchRequest{}

// UsersIdRolePatchRequest struct for UsersIdRolePatchRequest
type UsersIdRolePatchRequest struct {
	NewRoleName string `json:"newRoleName"`
}

type _UsersIdRolePatchRequest UsersIdRolePatchRequest

// NewUsersIdRolePatchRequest instantiates a new UsersIdRolePatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersIdRolePatchRequest(newRoleName string) *UsersIdRolePatchRequest {
	this := UsersIdRolePatchRequest{}
	this.NewRoleName = newRoleName
	return &this
}

// NewUsersIdRolePatchRequestWithDefaults instantiates a new UsersIdRolePatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersIdRolePatchRequestWithDefaults() *UsersIdRolePatchRequest {
	this := UsersIdRolePatchRequest{}
	return &this
}

// GetNewRoleName returns the NewRoleName field value
func (o *UsersIdRolePatchRequest) GetNewRoleName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NewRoleName
}

// GetNewRoleNameOk returns a tuple with the NewRoleName field value
// and a boolean to check if the value has been set.
func (o *UsersIdRolePatchRequest) GetNewRoleNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewRoleName, true
}

// SetNewRoleName sets field value
func (o *UsersIdRolePatchRequest) SetNewRoleName(v string) {
	o.NewRoleName = v
}

func (o UsersIdRolePatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersIdRolePatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["newRoleName"] = o.NewRoleName
	return toSerialize, nil
}

func (o *UsersIdRolePatchRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"newRoleName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsersIdRolePatchRequest := _UsersIdRolePatchRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsersIdRolePatchRequest)

	if err != nil {
		return err
	}

	*o = UsersIdRolePatchRequest(varUsersIdRolePatchRequest)

	return err
}

type NullableUsersIdRolePatchRequest struct {
	value *UsersIdRolePatchRequest
	isSet bool
}

func (v NullableUsersIdRolePatchRequest) Get() *UsersIdRolePatchRequest {
	return v.value
}

func (v *NullableUsersIdRolePatchRequest) Set(val *UsersIdRolePatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersIdRolePatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersIdRolePatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersIdRolePatchRequest(val *UsersIdRolePatchRequest) *NullableUsersIdRolePatchRequest {
	return &NullableUsersIdRolePatchRequest{value: val, isSet: true}
}

func (v NullableUsersIdRolePatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersIdRolePatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


