/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CreateCredentialResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCredentialResponse{}

// CreateCredentialResponse struct for CreateCredentialResponse
type CreateCredentialResponse struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type _CreateCredentialResponse CreateCredentialResponse

// NewCreateCredentialResponse instantiates a new CreateCredentialResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCredentialResponse(id string, name string, type_ string, createdAt time.Time, updatedAt time.Time) *CreateCredentialResponse {
	this := CreateCredentialResponse{}
	this.Id = id
	this.Name = name
	this.Type = type_
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewCreateCredentialResponseWithDefaults instantiates a new CreateCredentialResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCredentialResponseWithDefaults() *CreateCredentialResponse {
	this := CreateCredentialResponse{}
	return &this
}

// GetId returns the Id field value
func (o *CreateCredentialResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateCredentialResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateCredentialResponse) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *CreateCredentialResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateCredentialResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateCredentialResponse) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *CreateCredentialResponse) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateCredentialResponse) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateCredentialResponse) SetType(v string) {
	o.Type = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CreateCredentialResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CreateCredentialResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CreateCredentialResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *CreateCredentialResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *CreateCredentialResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *CreateCredentialResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o CreateCredentialResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCredentialResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *CreateCredentialResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"type",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCredentialResponse := _CreateCredentialResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCredentialResponse)

	if err != nil {
		return err
	}

	*o = CreateCredentialResponse(varCreateCredentialResponse)

	return err
}

type NullableCreateCredentialResponse struct {
	value *CreateCredentialResponse
	isSet bool
}

func (v NullableCreateCredentialResponse) Get() *CreateCredentialResponse {
	return v.value
}

func (v *NullableCreateCredentialResponse) Set(val *CreateCredentialResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCredentialResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCredentialResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCredentialResponse(val *CreateCredentialResponse) *NullableCreateCredentialResponse {
	return &NullableCreateCredentialResponse{value: val, isSet: true}
}

func (v NullableCreateCredentialResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCredentialResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


