/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateDataTableRequestColumnsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDataTableRequestColumnsInner{}

// CreateDataTableRequestColumnsInner struct for CreateDataTableRequestColumnsInner
type CreateDataTableRequestColumnsInner struct {
	// Column name
	Name string `json:"name"`
	// Column data type
	Type                 string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _CreateDataTableRequestColumnsInner CreateDataTableRequestColumnsInner

// NewCreateDataTableRequestColumnsInner instantiates a new CreateDataTableRequestColumnsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDataTableRequestColumnsInner(name string, type_ string) *CreateDataTableRequestColumnsInner {
	this := CreateDataTableRequestColumnsInner{}
	this.Name = name
	this.Type = type_
	return &this
}

// NewCreateDataTableRequestColumnsInnerWithDefaults instantiates a new CreateDataTableRequestColumnsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDataTableRequestColumnsInnerWithDefaults() *CreateDataTableRequestColumnsInner {
	this := CreateDataTableRequestColumnsInner{}
	return &this
}

// GetName returns the Name field value
func (o *CreateDataTableRequestColumnsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateDataTableRequestColumnsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateDataTableRequestColumnsInner) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *CreateDataTableRequestColumnsInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateDataTableRequestColumnsInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateDataTableRequestColumnsInner) SetType(v string) {
	o.Type = v
}

func (o CreateDataTableRequestColumnsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDataTableRequestColumnsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateDataTableRequestColumnsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDataTableRequestColumnsInner := _CreateDataTableRequestColumnsInner{}

	err = json.Unmarshal(data, &varCreateDataTableRequestColumnsInner)

	if err != nil {
		return err
	}

	*o = CreateDataTableRequestColumnsInner(varCreateDataTableRequestColumnsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateDataTableRequestColumnsInner struct {
	value *CreateDataTableRequestColumnsInner
	isSet bool
}

func (v NullableCreateDataTableRequestColumnsInner) Get() *CreateDataTableRequestColumnsInner {
	return v.value
}

func (v *NullableCreateDataTableRequestColumnsInner) Set(val *CreateDataTableRequestColumnsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDataTableRequestColumnsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDataTableRequestColumnsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDataTableRequestColumnsInner(val *CreateDataTableRequestColumnsInner) *NullableCreateDataTableRequestColumnsInner {
	return &NullableCreateDataTableRequestColumnsInner{value: val, isSet: true}
}

func (v NullableCreateDataTableRequestColumnsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDataTableRequestColumnsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
