/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
)

// checks if the TagList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagList{}

// TagList struct for TagList
type TagList struct {
	Data []Tag `json:"data,omitempty"`
	// Paginate through tags by setting the cursor parameter to a nextCursor attribute returned by a previous request. Default value fetches the first \"page\" of the collection.
	NextCursor NullableString `json:"nextCursor,omitempty"`
}

// NewTagList instantiates a new TagList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagList() *TagList {
	this := TagList{}
	return &this
}

// NewTagListWithDefaults instantiates a new TagList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagListWithDefaults() *TagList {
	this := TagList{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *TagList) GetData() []Tag {
	if o == nil || IsNil(o.Data) {
		var ret []Tag
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TagList) GetDataOk() ([]Tag, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *TagList) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Tag and assigns it to the Data field.
func (o *TagList) SetData(v []Tag) {
	o.Data = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TagList) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor.Get()) {
		var ret string
		return ret
	}
	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TagList) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// HasNextCursor returns a boolean if a field has been set.
func (o *TagList) HasNextCursor() bool {
	if o != nil && o.NextCursor.IsSet() {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given NullableString and assigns it to the NextCursor field.
func (o *TagList) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}
// SetNextCursorNil sets the value for NextCursor to be an explicit nil
func (o *TagList) SetNextCursorNil() {
	o.NextCursor.Set(nil)
}

// UnsetNextCursor ensures that no value is present for NextCursor, not even an explicit nil
func (o *TagList) UnsetNextCursor() {
	o.NextCursor.Unset()
}

func (o TagList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if o.NextCursor.IsSet() {
		toSerialize["nextCursor"] = o.NextCursor.Get()
	}
	return toSerialize, nil
}

type NullableTagList struct {
	value *TagList
	isSet bool
}

func (v NullableTagList) Get() *TagList {
	return v.value
}

func (v *NullableTagList) Set(val *TagList) {
	v.value = val
	v.isSet = true
}

func (v NullableTagList) IsSet() bool {
	return v.isSet
}

func (v *NullableTagList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagList(val *TagList) *NullableTagList {
	return &NullableTagList{value: val, isSet: true}
}

func (v NullableTagList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


