/*
n8n Public API

n8n Public API

API version: 2.0.0
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"time"
)

// WorkflowVersion represents a specific version of a workflow from workflow history.
type WorkflowVersion struct {
	// The version ID of this workflow snapshot.
	VersionID string `json:"versionId"`
	// The workflow ID this version belongs to.
	WorkflowID string `json:"workflowId"`
	// Workflow name at this version.
	Name *string `json:"name,omitempty"`
	// Workflow description at this version.
	Description *string `json:"description,omitempty"`
	// Authors who created this version.
	Authors *string `json:"authors,omitempty"`
	// Nodes as they were in this version.
	Nodes []Node `json:"nodes"`
	// Connections as they were in this version.
	Connections interface{} `json:"connections"`
	// When this version was created.
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// When this version was last updated.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}
