/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
)

// checks if the VariableList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VariableList{}

// VariableList struct for VariableList
type VariableList struct {
	Data []Variable `json:"data,omitempty"`
	// Paginate through variables by setting the cursor parameter to a nextCursor attribute returned by a previous request. Default value fetches the first \"page\" of the collection.
	NextCursor NullableString `json:"nextCursor,omitempty"`
}

// NewVariableList instantiates a new VariableList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVariableList() *VariableList {
	this := VariableList{}
	return &this
}

// NewVariableListWithDefaults instantiates a new VariableList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVariableListWithDefaults() *VariableList {
	this := VariableList{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *VariableList) GetData() []Variable {
	if o == nil || IsNil(o.Data) {
		var ret []Variable
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VariableList) GetDataOk() ([]Variable, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *VariableList) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Variable and assigns it to the Data field.
func (o *VariableList) SetData(v []Variable) {
	o.Data = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VariableList) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor.Get()) {
		var ret string
		return ret
	}
	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VariableList) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// HasNextCursor returns a boolean if a field has been set.
func (o *VariableList) HasNextCursor() bool {
	if o != nil && o.NextCursor.IsSet() {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given NullableString and assigns it to the NextCursor field.
func (o *VariableList) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}

// SetNextCursorNil sets the value for NextCursor to be an explicit nil
func (o *VariableList) SetNextCursorNil() {
	o.NextCursor.Set(nil)
}

// UnsetNextCursor ensures that no value is present for NextCursor, not even an explicit nil
func (o *VariableList) UnsetNextCursor() {
	o.NextCursor.Unset()
}

func (o VariableList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VariableList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if o.NextCursor.IsSet() {
		toSerialize["nextCursor"] = o.NextCursor.Get()
	}
	return toSerialize, nil
}

type NullableVariableList struct {
	value *VariableList
	isSet bool
}

func (v NullableVariableList) Get() *VariableList {
	return v.value
}

func (v *NullableVariableList) Set(val *VariableList) {
	v.value = val
	v.isSet = true
}

func (v NullableVariableList) IsSet() bool {
	return v.isSet
}

func (v *NullableVariableList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVariableList(val *VariableList) *NullableVariableList {
	return &NullableVariableList{value: val, isSet: true}
}

func (v NullableVariableList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVariableList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
