/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the InsertRowsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InsertRowsRequest{}

// InsertRowsRequest struct for InsertRowsRequest
type InsertRowsRequest struct {
	// Array of rows to insert. Each row is an object with column names as keys.
	Data []map[string]interface{} `json:"data"`
	// - count: Return only the number of rows inserted - id: Return an array of inserted row IDs - all: Return the full row data for all inserted rows
	ReturnType           *string `json:"returnType,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InsertRowsRequest InsertRowsRequest

// NewInsertRowsRequest instantiates a new InsertRowsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInsertRowsRequest(data []map[string]interface{}) *InsertRowsRequest {
	this := InsertRowsRequest{}
	this.Data = data
	var returnType string = "count"
	this.ReturnType = &returnType
	return &this
}

// NewInsertRowsRequestWithDefaults instantiates a new InsertRowsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInsertRowsRequestWithDefaults() *InsertRowsRequest {
	this := InsertRowsRequest{}
	var returnType string = "count"
	this.ReturnType = &returnType
	return &this
}

// GetData returns the Data field value
func (o *InsertRowsRequest) GetData() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *InsertRowsRequest) GetDataOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *InsertRowsRequest) SetData(v []map[string]interface{}) {
	o.Data = v
}

// GetReturnType returns the ReturnType field value if set, zero value otherwise.
func (o *InsertRowsRequest) GetReturnType() string {
	if o == nil || IsNil(o.ReturnType) {
		var ret string
		return ret
	}
	return *o.ReturnType
}

// GetReturnTypeOk returns a tuple with the ReturnType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InsertRowsRequest) GetReturnTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ReturnType) {
		return nil, false
	}
	return o.ReturnType, true
}

// HasReturnType returns a boolean if a field has been set.
func (o *InsertRowsRequest) HasReturnType() bool {
	if o != nil && !IsNil(o.ReturnType) {
		return true
	}

	return false
}

// SetReturnType gets a reference to the given string and assigns it to the ReturnType field.
func (o *InsertRowsRequest) SetReturnType(v string) {
	o.ReturnType = &v
}

func (o InsertRowsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InsertRowsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if !IsNil(o.ReturnType) {
		toSerialize["returnType"] = o.ReturnType
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InsertRowsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInsertRowsRequest := _InsertRowsRequest{}

	err = json.Unmarshal(data, &varInsertRowsRequest)

	if err != nil {
		return err
	}

	*o = InsertRowsRequest(varInsertRowsRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "returnType")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInsertRowsRequest struct {
	value *InsertRowsRequest
	isSet bool
}

func (v NullableInsertRowsRequest) Get() *InsertRowsRequest {
	return v.value
}

func (v *NullableInsertRowsRequest) Set(val *InsertRowsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInsertRowsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInsertRowsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInsertRowsRequest(val *InsertRowsRequest) *NullableInsertRowsRequest {
	return &NullableInsertRowsRequest{value: val, isSet: true}
}

func (v NullableInsertRowsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInsertRowsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
