/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsersPostRequestInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersPostRequestInner{}

// UsersPostRequestInner struct for UsersPostRequestInner
type UsersPostRequestInner struct {
	Email string `json:"email"`
	Role *string `json:"role,omitempty"`
}

type _UsersPostRequestInner UsersPostRequestInner

// NewUsersPostRequestInner instantiates a new UsersPostRequestInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersPostRequestInner(email string) *UsersPostRequestInner {
	this := UsersPostRequestInner{}
	this.Email = email
	return &this
}

// NewUsersPostRequestInnerWithDefaults instantiates a new UsersPostRequestInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersPostRequestInnerWithDefaults() *UsersPostRequestInner {
	this := UsersPostRequestInner{}
	return &this
}

// GetEmail returns the Email field value
func (o *UsersPostRequestInner) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *UsersPostRequestInner) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *UsersPostRequestInner) SetEmail(v string) {
	o.Email = v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *UsersPostRequestInner) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersPostRequestInner) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *UsersPostRequestInner) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *UsersPostRequestInner) SetRole(v string) {
	o.Role = &v
}

func (o UsersPostRequestInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersPostRequestInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	return toSerialize, nil
}

func (o *UsersPostRequestInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsersPostRequestInner := _UsersPostRequestInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsersPostRequestInner)

	if err != nil {
		return err
	}

	*o = UsersPostRequestInner(varUsersPostRequestInner)

	return err
}

type NullableUsersPostRequestInner struct {
	value *UsersPostRequestInner
	isSet bool
}

func (v NullableUsersPostRequestInner) Get() *UsersPostRequestInner {
	return v.value
}

func (v *NullableUsersPostRequestInner) Set(val *UsersPostRequestInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersPostRequestInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersPostRequestInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersPostRequestInner(val *UsersPostRequestInner) *NullableUsersPostRequestInner {
	return &NullableUsersPostRequestInner{value: val, isSet: true}
}

func (v NullableUsersPostRequestInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersPostRequestInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


