/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// DeleteDataTableRows200Response - struct for DeleteDataTableRows200Response
type DeleteDataTableRows200Response struct {
	ArrayOfDataTableRow *[]DataTableRow
	Bool                *bool
}

// []DataTableRowAsDeleteDataTableRows200Response is a convenience function that returns []DataTableRow wrapped in DeleteDataTableRows200Response
func ArrayOfDataTableRowAsDeleteDataTableRows200Response(v *[]DataTableRow) DeleteDataTableRows200Response {
	return DeleteDataTableRows200Response{
		ArrayOfDataTableRow: v,
	}
}

// boolAsDeleteDataTableRows200Response is a convenience function that returns bool wrapped in DeleteDataTableRows200Response
func BoolAsDeleteDataTableRows200Response(v *bool) DeleteDataTableRows200Response {
	return DeleteDataTableRows200Response{
		Bool: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *DeleteDataTableRows200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ArrayOfDataTableRow
	err = newStrictDecoder(data).Decode(&dst.ArrayOfDataTableRow)
	if err == nil {
		jsonArrayOfDataTableRow, _ := json.Marshal(dst.ArrayOfDataTableRow)
		if string(jsonArrayOfDataTableRow) == "{}" { // empty struct
			dst.ArrayOfDataTableRow = nil
		} else {
			if err = validator.Validate(dst.ArrayOfDataTableRow); err != nil {
				dst.ArrayOfDataTableRow = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfDataTableRow = nil
	}

	// try to unmarshal data into Bool
	err = newStrictDecoder(data).Decode(&dst.Bool)
	if err == nil {
		jsonBool, _ := json.Marshal(dst.Bool)
		if string(jsonBool) == "{}" { // empty struct
			dst.Bool = nil
		} else {
			if err = validator.Validate(dst.Bool); err != nil {
				dst.Bool = nil
			} else {
				match++
			}
		}
	} else {
		dst.Bool = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ArrayOfDataTableRow = nil
		dst.Bool = nil

		return fmt.Errorf("data matches more than one schema in oneOf(DeleteDataTableRows200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(DeleteDataTableRows200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src DeleteDataTableRows200Response) MarshalJSON() ([]byte, error) {
	if src.ArrayOfDataTableRow != nil {
		return json.Marshal(&src.ArrayOfDataTableRow)
	}

	if src.Bool != nil {
		return json.Marshal(&src.Bool)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *DeleteDataTableRows200Response) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.ArrayOfDataTableRow != nil {
		return obj.ArrayOfDataTableRow
	}

	if obj.Bool != nil {
		return obj.Bool
	}

	// all schemas are nil
	return nil
}

type NullableDeleteDataTableRows200Response struct {
	value *DeleteDataTableRows200Response
	isSet bool
}

func (v NullableDeleteDataTableRows200Response) Get() *DeleteDataTableRows200Response {
	return v.value
}

func (v *NullableDeleteDataTableRows200Response) Set(val *DeleteDataTableRows200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteDataTableRows200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteDataTableRows200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteDataTableRows200Response(val *DeleteDataTableRows200Response) *NullableDeleteDataTableRows200Response {
	return &NullableDeleteDataTableRows200Response{value: val, isSet: true}
}

func (v NullableDeleteDataTableRows200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteDataTableRows200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
