/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
)

// checks if the Pull type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Pull{}

// Pull struct for Pull
type Pull struct {
	Force *bool `json:"force,omitempty"`
	Variables map[string]interface{} `json:"variables,omitempty"`
}

// NewPull instantiates a new Pull object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPull() *Pull {
	this := Pull{}
	return &this
}

// NewPullWithDefaults instantiates a new Pull object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPullWithDefaults() *Pull {
	this := Pull{}
	return &this
}

// GetForce returns the Force field value if set, zero value otherwise.
func (o *Pull) GetForce() bool {
	if o == nil || IsNil(o.Force) {
		var ret bool
		return ret
	}
	return *o.Force
}

// GetForceOk returns a tuple with the Force field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Pull) GetForceOk() (*bool, bool) {
	if o == nil || IsNil(o.Force) {
		return nil, false
	}
	return o.Force, true
}

// HasForce returns a boolean if a field has been set.
func (o *Pull) HasForce() bool {
	if o != nil && !IsNil(o.Force) {
		return true
	}

	return false
}

// SetForce gets a reference to the given bool and assigns it to the Force field.
func (o *Pull) SetForce(v bool) {
	o.Force = &v
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *Pull) GetVariables() map[string]interface{} {
	if o == nil || IsNil(o.Variables) {
		var ret map[string]interface{}
		return ret
	}
	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Pull) GetVariablesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Variables) {
		return map[string]interface{}{}, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *Pull) HasVariables() bool {
	if o != nil && !IsNil(o.Variables) {
		return true
	}

	return false
}

// SetVariables gets a reference to the given map[string]interface{} and assigns it to the Variables field.
func (o *Pull) SetVariables(v map[string]interface{}) {
	o.Variables = v
}

func (o Pull) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Pull) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Force) {
		toSerialize["force"] = o.Force
	}
	if !IsNil(o.Variables) {
		toSerialize["variables"] = o.Variables
	}
	return toSerialize, nil
}

type NullablePull struct {
	value *Pull
	isSet bool
}

func (v NullablePull) Get() *Pull {
	return v.value
}

func (v *NullablePull) Set(val *Pull) {
	v.value = val
	v.isSet = true
}

func (v NullablePull) IsSet() bool {
	return v.isSet
}

func (v *NullablePull) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePull(val *Pull) *NullablePull {
	return &NullablePull{value: val, isSet: true}
}

func (v NullablePull) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePull) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


