/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
)

// checks if the CredentialList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CredentialList{}

// CredentialList struct for CredentialList
type CredentialList struct {
	Data []CredentialListItem `json:"data,omitempty"`
	// Paginate through credentials by setting the cursor parameter to a nextCursor attribute returned by a previous request. Default value fetches the first \"page\" of the collection.
	NextCursor           NullableString `json:"nextCursor,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CredentialList CredentialList

// NewCredentialList instantiates a new CredentialList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialList() *CredentialList {
	this := CredentialList{}
	return &this
}

// NewCredentialListWithDefaults instantiates a new CredentialList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialListWithDefaults() *CredentialList {
	this := CredentialList{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CredentialList) GetData() []CredentialListItem {
	if o == nil || IsNil(o.Data) {
		var ret []CredentialListItem
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialList) GetDataOk() ([]CredentialListItem, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CredentialList) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []CredentialListItem and assigns it to the Data field.
func (o *CredentialList) SetData(v []CredentialListItem) {
	o.Data = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CredentialList) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor.Get()) {
		var ret string
		return ret
	}
	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CredentialList) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// HasNextCursor returns a boolean if a field has been set.
func (o *CredentialList) HasNextCursor() bool {
	if o != nil && o.NextCursor.IsSet() {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given NullableString and assigns it to the NextCursor field.
func (o *CredentialList) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}

// SetNextCursorNil sets the value for NextCursor to be an explicit nil
func (o *CredentialList) SetNextCursorNil() {
	o.NextCursor.Set(nil)
}

// UnsetNextCursor ensures that no value is present for NextCursor, not even an explicit nil
func (o *CredentialList) UnsetNextCursor() {
	o.NextCursor.Unset()
}

func (o CredentialList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CredentialList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if o.NextCursor.IsSet() {
		toSerialize["nextCursor"] = o.NextCursor.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CredentialList) UnmarshalJSON(data []byte) (err error) {
	varCredentialList := _CredentialList{}

	err = json.Unmarshal(data, &varCredentialList)

	if err != nil {
		return err
	}

	*o = CredentialList(varCredentialList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "nextCursor")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCredentialList struct {
	value *CredentialList
	isSet bool
}

func (v NullableCredentialList) Get() *CredentialList {
	return v.value
}

func (v *NullableCredentialList) Set(val *CredentialList) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialList) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialList(val *CredentialList) *NullableCredentialList {
	return &NullableCredentialList{value: val, isSet: true}
}

func (v NullableCredentialList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
