/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
)

// checks if the ProjectMemberList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectMemberList{}

// ProjectMemberList struct for ProjectMemberList
type ProjectMemberList struct {
	Data []ProjectMember `json:"data,omitempty"`
	// Paginate through project members by setting the cursor parameter to the nextCursor attribute returned by a previous request. Default value fetches the first page of the collection.
	NextCursor           NullableString `json:"nextCursor,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProjectMemberList ProjectMemberList

// NewProjectMemberList instantiates a new ProjectMemberList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectMemberList() *ProjectMemberList {
	this := ProjectMemberList{}
	return &this
}

// NewProjectMemberListWithDefaults instantiates a new ProjectMemberList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectMemberListWithDefaults() *ProjectMemberList {
	this := ProjectMemberList{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ProjectMemberList) GetData() []ProjectMember {
	if o == nil || IsNil(o.Data) {
		var ret []ProjectMember
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectMemberList) GetDataOk() ([]ProjectMember, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ProjectMemberList) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ProjectMember and assigns it to the Data field.
func (o *ProjectMemberList) SetData(v []ProjectMember) {
	o.Data = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectMemberList) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor.Get()) {
		var ret string
		return ret
	}
	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectMemberList) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// HasNextCursor returns a boolean if a field has been set.
func (o *ProjectMemberList) HasNextCursor() bool {
	if o != nil && o.NextCursor.IsSet() {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given NullableString and assigns it to the NextCursor field.
func (o *ProjectMemberList) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}

// SetNextCursorNil sets the value for NextCursor to be an explicit nil
func (o *ProjectMemberList) SetNextCursorNil() {
	o.NextCursor.Set(nil)
}

// UnsetNextCursor ensures that no value is present for NextCursor, not even an explicit nil
func (o *ProjectMemberList) UnsetNextCursor() {
	o.NextCursor.Unset()
}

func (o ProjectMemberList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectMemberList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if o.NextCursor.IsSet() {
		toSerialize["nextCursor"] = o.NextCursor.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProjectMemberList) UnmarshalJSON(data []byte) (err error) {
	varProjectMemberList := _ProjectMemberList{}

	err = json.Unmarshal(data, &varProjectMemberList)

	if err != nil {
		return err
	}

	*o = ProjectMemberList(varProjectMemberList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "nextCursor")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProjectMemberList struct {
	value *ProjectMemberList
	isSet bool
}

func (v NullableProjectMemberList) Get() *ProjectMemberList {
	return v.value
}

func (v *NullableProjectMemberList) Set(val *ProjectMemberList) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectMemberList) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectMemberList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectMemberList(val *ProjectMemberList) *NullableProjectMemberList {
	return &NullableProjectMemberList{value: val, isSet: true}
}

func (v NullableProjectMemberList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectMemberList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
