/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
	"time"
)

// checks if the ActiveVersion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActiveVersion{}

// ActiveVersion struct for ActiveVersion
type ActiveVersion struct {
	// Unique identifier for this workflow version
	VersionId *string `json:"versionId,omitempty"`
	// The workflow this version belongs to
	WorkflowId  *string                `json:"workflowId,omitempty"`
	Nodes       []Node                 `json:"nodes,omitempty"`
	Connections map[string]interface{} `json:"connections,omitempty"`
	// Comma-separated list of author IDs who contributed to this version
	Authors              *string    `json:"authors,omitempty"`
	CreatedAt            *time.Time `json:"createdAt,omitempty"`
	UpdatedAt            *time.Time `json:"updatedAt,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ActiveVersion ActiveVersion

// NewActiveVersion instantiates a new ActiveVersion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActiveVersion() *ActiveVersion {
	this := ActiveVersion{}
	return &this
}

// NewActiveVersionWithDefaults instantiates a new ActiveVersion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActiveVersionWithDefaults() *ActiveVersion {
	this := ActiveVersion{}
	return &this
}

// GetVersionId returns the VersionId field value if set, zero value otherwise.
func (o *ActiveVersion) GetVersionId() string {
	if o == nil || IsNil(o.VersionId) {
		var ret string
		return ret
	}
	return *o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveVersion) GetVersionIdOk() (*string, bool) {
	if o == nil || IsNil(o.VersionId) {
		return nil, false
	}
	return o.VersionId, true
}

// HasVersionId returns a boolean if a field has been set.
func (o *ActiveVersion) HasVersionId() bool {
	if o != nil && !IsNil(o.VersionId) {
		return true
	}

	return false
}

// SetVersionId gets a reference to the given string and assigns it to the VersionId field.
func (o *ActiveVersion) SetVersionId(v string) {
	o.VersionId = &v
}

// GetWorkflowId returns the WorkflowId field value if set, zero value otherwise.
func (o *ActiveVersion) GetWorkflowId() string {
	if o == nil || IsNil(o.WorkflowId) {
		var ret string
		return ret
	}
	return *o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveVersion) GetWorkflowIdOk() (*string, bool) {
	if o == nil || IsNil(o.WorkflowId) {
		return nil, false
	}
	return o.WorkflowId, true
}

// HasWorkflowId returns a boolean if a field has been set.
func (o *ActiveVersion) HasWorkflowId() bool {
	if o != nil && !IsNil(o.WorkflowId) {
		return true
	}

	return false
}

// SetWorkflowId gets a reference to the given string and assigns it to the WorkflowId field.
func (o *ActiveVersion) SetWorkflowId(v string) {
	o.WorkflowId = &v
}

// GetNodes returns the Nodes field value if set, zero value otherwise.
func (o *ActiveVersion) GetNodes() []Node {
	if o == nil || IsNil(o.Nodes) {
		var ret []Node
		return ret
	}
	return o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveVersion) GetNodesOk() ([]Node, bool) {
	if o == nil || IsNil(o.Nodes) {
		return nil, false
	}
	return o.Nodes, true
}

// HasNodes returns a boolean if a field has been set.
func (o *ActiveVersion) HasNodes() bool {
	if o != nil && !IsNil(o.Nodes) {
		return true
	}

	return false
}

// SetNodes gets a reference to the given []Node and assigns it to the Nodes field.
func (o *ActiveVersion) SetNodes(v []Node) {
	o.Nodes = v
}

// GetConnections returns the Connections field value if set, zero value otherwise.
func (o *ActiveVersion) GetConnections() map[string]interface{} {
	if o == nil || IsNil(o.Connections) {
		var ret map[string]interface{}
		return ret
	}
	return o.Connections
}

// GetConnectionsOk returns a tuple with the Connections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveVersion) GetConnectionsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Connections) {
		return map[string]interface{}{}, false
	}
	return o.Connections, true
}

// HasConnections returns a boolean if a field has been set.
func (o *ActiveVersion) HasConnections() bool {
	if o != nil && !IsNil(o.Connections) {
		return true
	}

	return false
}

// SetConnections gets a reference to the given map[string]interface{} and assigns it to the Connections field.
func (o *ActiveVersion) SetConnections(v map[string]interface{}) {
	o.Connections = v
}

// GetAuthors returns the Authors field value if set, zero value otherwise.
func (o *ActiveVersion) GetAuthors() string {
	if o == nil || IsNil(o.Authors) {
		var ret string
		return ret
	}
	return *o.Authors
}

// GetAuthorsOk returns a tuple with the Authors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveVersion) GetAuthorsOk() (*string, bool) {
	if o == nil || IsNil(o.Authors) {
		return nil, false
	}
	return o.Authors, true
}

// HasAuthors returns a boolean if a field has been set.
func (o *ActiveVersion) HasAuthors() bool {
	if o != nil && !IsNil(o.Authors) {
		return true
	}

	return false
}

// SetAuthors gets a reference to the given string and assigns it to the Authors field.
func (o *ActiveVersion) SetAuthors(v string) {
	o.Authors = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ActiveVersion) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveVersion) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ActiveVersion) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *ActiveVersion) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ActiveVersion) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveVersion) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ActiveVersion) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *ActiveVersion) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o ActiveVersion) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActiveVersion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VersionId) {
		toSerialize["versionId"] = o.VersionId
	}
	if !IsNil(o.WorkflowId) {
		toSerialize["workflowId"] = o.WorkflowId
	}
	if !IsNil(o.Nodes) {
		toSerialize["nodes"] = o.Nodes
	}
	if !IsNil(o.Connections) {
		toSerialize["connections"] = o.Connections
	}
	if !IsNil(o.Authors) {
		toSerialize["authors"] = o.Authors
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ActiveVersion) UnmarshalJSON(data []byte) (err error) {
	varActiveVersion := _ActiveVersion{}

	err = json.Unmarshal(data, &varActiveVersion)

	if err != nil {
		return err
	}

	*o = ActiveVersion(varActiveVersion)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "versionId")
		delete(additionalProperties, "workflowId")
		delete(additionalProperties, "nodes")
		delete(additionalProperties, "connections")
		delete(additionalProperties, "authors")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableActiveVersion struct {
	value *ActiveVersion
	isSet bool
}

func (v NullableActiveVersion) Get() *ActiveVersion {
	return v.value
}

func (v *NullableActiveVersion) Set(val *ActiveVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableActiveVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableActiveVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActiveVersion(val *ActiveVersion) *NullableActiveVersion {
	return &NullableActiveVersion{value: val, isSet: true}
}

func (v NullableActiveVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActiveVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
