/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
)

// checks if the UsersPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersPost200Response{}

// UsersPost200Response struct for UsersPost200Response
type UsersPost200Response struct {
	User                 *UsersPost200ResponseUser `json:"user,omitempty"`
	Error                *string                   `json:"error,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UsersPost200Response UsersPost200Response

// NewUsersPost200Response instantiates a new UsersPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersPost200Response() *UsersPost200Response {
	this := UsersPost200Response{}
	return &this
}

// NewUsersPost200ResponseWithDefaults instantiates a new UsersPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersPost200ResponseWithDefaults() *UsersPost200Response {
	this := UsersPost200Response{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *UsersPost200Response) GetUser() UsersPost200ResponseUser {
	if o == nil || IsNil(o.User) {
		var ret UsersPost200ResponseUser
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersPost200Response) GetUserOk() (*UsersPost200ResponseUser, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *UsersPost200Response) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given UsersPost200ResponseUser and assigns it to the User field.
func (o *UsersPost200Response) SetUser(v UsersPost200ResponseUser) {
	o.User = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *UsersPost200Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersPost200Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *UsersPost200Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *UsersPost200Response) SetError(v string) {
	o.Error = &v
}

func (o UsersPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UsersPost200Response) UnmarshalJSON(data []byte) (err error) {
	varUsersPost200Response := _UsersPost200Response{}

	err = json.Unmarshal(data, &varUsersPost200Response)

	if err != nil {
		return err
	}

	*o = UsersPost200Response(varUsersPost200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "user")
		delete(additionalProperties, "error")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUsersPost200Response struct {
	value *UsersPost200Response
	isSet bool
}

func (v NullableUsersPost200Response) Get() *UsersPost200Response {
	return v.value
}

func (v *NullableUsersPost200Response) Set(val *UsersPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersPost200Response(val *UsersPost200Response) *NullableUsersPost200Response {
	return &NullableUsersPost200Response{value: val, isSet: true}
}

func (v NullableUsersPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
