/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the ProjectsProjectIdUsersPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectsProjectIdUsersPostRequest{}

// ProjectsProjectIdUsersPostRequest struct for ProjectsProjectIdUsersPostRequest
type ProjectsProjectIdUsersPostRequest struct {
	// A list of userIds and roles to add to the project.
	Relations            []ProjectsProjectIdUsersPostRequestRelationsInner `json:"relations"`
	AdditionalProperties map[string]interface{}
}

type _ProjectsProjectIdUsersPostRequest ProjectsProjectIdUsersPostRequest

// NewProjectsProjectIdUsersPostRequest instantiates a new ProjectsProjectIdUsersPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectsProjectIdUsersPostRequest(relations []ProjectsProjectIdUsersPostRequestRelationsInner) *ProjectsProjectIdUsersPostRequest {
	this := ProjectsProjectIdUsersPostRequest{}
	this.Relations = relations
	return &this
}

// NewProjectsProjectIdUsersPostRequestWithDefaults instantiates a new ProjectsProjectIdUsersPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectsProjectIdUsersPostRequestWithDefaults() *ProjectsProjectIdUsersPostRequest {
	this := ProjectsProjectIdUsersPostRequest{}
	return &this
}

// GetRelations returns the Relations field value
func (o *ProjectsProjectIdUsersPostRequest) GetRelations() []ProjectsProjectIdUsersPostRequestRelationsInner {
	if o == nil {
		var ret []ProjectsProjectIdUsersPostRequestRelationsInner
		return ret
	}

	return o.Relations
}

// GetRelationsOk returns a tuple with the Relations field value
// and a boolean to check if the value has been set.
func (o *ProjectsProjectIdUsersPostRequest) GetRelationsOk() ([]ProjectsProjectIdUsersPostRequestRelationsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Relations, true
}

// SetRelations sets field value
func (o *ProjectsProjectIdUsersPostRequest) SetRelations(v []ProjectsProjectIdUsersPostRequestRelationsInner) {
	o.Relations = v
}

func (o ProjectsProjectIdUsersPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectsProjectIdUsersPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["relations"] = o.Relations

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProjectsProjectIdUsersPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"relations",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectsProjectIdUsersPostRequest := _ProjectsProjectIdUsersPostRequest{}

	err = json.Unmarshal(data, &varProjectsProjectIdUsersPostRequest)

	if err != nil {
		return err
	}

	*o = ProjectsProjectIdUsersPostRequest(varProjectsProjectIdUsersPostRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "relations")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProjectsProjectIdUsersPostRequest struct {
	value *ProjectsProjectIdUsersPostRequest
	isSet bool
}

func (v NullableProjectsProjectIdUsersPostRequest) Get() *ProjectsProjectIdUsersPostRequest {
	return v.value
}

func (v *NullableProjectsProjectIdUsersPostRequest) Set(val *ProjectsProjectIdUsersPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectsProjectIdUsersPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectsProjectIdUsersPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectsProjectIdUsersPostRequest(val *ProjectsProjectIdUsersPostRequest) *NullableProjectsProjectIdUsersPostRequest {
	return &NullableProjectsProjectIdUsersPostRequest{value: val, isSet: true}
}

func (v NullableProjectsProjectIdUsersPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectsProjectIdUsersPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
