/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
)

// checks if the WorkflowSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowSettings{}

// WorkflowSettings struct for WorkflowSettings
type WorkflowSettings struct {
	SaveExecutionProgress    *bool    `json:"saveExecutionProgress,omitempty"`
	SaveManualExecutions     *bool    `json:"saveManualExecutions,omitempty"`
	SaveDataErrorExecution   *string  `json:"saveDataErrorExecution,omitempty"`
	SaveDataSuccessExecution *string  `json:"saveDataSuccessExecution,omitempty"`
	ExecutionTimeout         *float32 `json:"executionTimeout,omitempty"`
	// The ID of the workflow that contains the error trigger node.
	ErrorWorkflow  *string `json:"errorWorkflow,omitempty"`
	Timezone       *string `json:"timezone,omitempty"`
	ExecutionOrder *string `json:"executionOrder,omitempty"`
	// Controls which workflows are allowed to call this workflow using the Execute Workflow node.  Available options: - `any`: Any workflow can call this workflow (no restrictions) - `none`: No other workflows can call this workflow (completely blocked) - `workflowsFromSameOwner` (default): Only workflows owned by the same project can call this workflow   * For personal projects: Only workflows created by the same user   * For team projects: Only workflows within the same team project - `workflowsFromAList`: Only specific workflows listed in the `callerIds` field can call this workflow   * Requires the `callerIds` field to specify which workflow IDs are allowed   * See `callerIds` field documentation for usage
	CallerPolicy *string `json:"callerPolicy,omitempty"`
	// Comma-separated list of workflow IDs allowed to call this workflow (only used with workflowsFromAList policy)
	CallerIds *string `json:"callerIds,omitempty"`
	// Estimated time saved per execution in minutes
	TimeSavedPerExecution *float32 `json:"timeSavedPerExecution,omitempty"`
	// Controls whether this workflow is accessible via the Model Context Protocol (MCP).  When enabled, this workflow can be called by MCP clients (AI assistants and other tools that support MCP). This allows external AI tools to discover and execute this workflow as part of their capabilities.  Requirements for enabling MCP access: - The workflow must be active (not deactivated) - The workflow must contain at least one active Webhook node - Only webhook-triggered workflows can be exposed via MCP  Security note: When a workflow is available in MCP, it can be discovered and executed by any MCP client that has the appropriate API credentials for your n8n instance.
	AvailableInMCP       *bool `json:"availableInMCP,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WorkflowSettings WorkflowSettings

// NewWorkflowSettings instantiates a new WorkflowSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowSettings() *WorkflowSettings {
	this := WorkflowSettings{}
	var callerPolicy string = "workflowsFromSameOwner"
	this.CallerPolicy = &callerPolicy
	var availableInMCP bool = false
	this.AvailableInMCP = &availableInMCP
	return &this
}

// NewWorkflowSettingsWithDefaults instantiates a new WorkflowSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowSettingsWithDefaults() *WorkflowSettings {
	this := WorkflowSettings{}
	var callerPolicy string = "workflowsFromSameOwner"
	this.CallerPolicy = &callerPolicy
	var availableInMCP bool = false
	this.AvailableInMCP = &availableInMCP
	return &this
}

// GetSaveExecutionProgress returns the SaveExecutionProgress field value if set, zero value otherwise.
func (o *WorkflowSettings) GetSaveExecutionProgress() bool {
	if o == nil || IsNil(o.SaveExecutionProgress) {
		var ret bool
		return ret
	}
	return *o.SaveExecutionProgress
}

// GetSaveExecutionProgressOk returns a tuple with the SaveExecutionProgress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowSettings) GetSaveExecutionProgressOk() (*bool, bool) {
	if o == nil || IsNil(o.SaveExecutionProgress) {
		return nil, false
	}
	return o.SaveExecutionProgress, true
}

// HasSaveExecutionProgress returns a boolean if a field has been set.
func (o *WorkflowSettings) HasSaveExecutionProgress() bool {
	if o != nil && !IsNil(o.SaveExecutionProgress) {
		return true
	}

	return false
}

// SetSaveExecutionProgress gets a reference to the given bool and assigns it to the SaveExecutionProgress field.
func (o *WorkflowSettings) SetSaveExecutionProgress(v bool) {
	o.SaveExecutionProgress = &v
}

// GetSaveManualExecutions returns the SaveManualExecutions field value if set, zero value otherwise.
func (o *WorkflowSettings) GetSaveManualExecutions() bool {
	if o == nil || IsNil(o.SaveManualExecutions) {
		var ret bool
		return ret
	}
	return *o.SaveManualExecutions
}

// GetSaveManualExecutionsOk returns a tuple with the SaveManualExecutions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowSettings) GetSaveManualExecutionsOk() (*bool, bool) {
	if o == nil || IsNil(o.SaveManualExecutions) {
		return nil, false
	}
	return o.SaveManualExecutions, true
}

// HasSaveManualExecutions returns a boolean if a field has been set.
func (o *WorkflowSettings) HasSaveManualExecutions() bool {
	if o != nil && !IsNil(o.SaveManualExecutions) {
		return true
	}

	return false
}

// SetSaveManualExecutions gets a reference to the given bool and assigns it to the SaveManualExecutions field.
func (o *WorkflowSettings) SetSaveManualExecutions(v bool) {
	o.SaveManualExecutions = &v
}

// GetSaveDataErrorExecution returns the SaveDataErrorExecution field value if set, zero value otherwise.
func (o *WorkflowSettings) GetSaveDataErrorExecution() string {
	if o == nil || IsNil(o.SaveDataErrorExecution) {
		var ret string
		return ret
	}
	return *o.SaveDataErrorExecution
}

// GetSaveDataErrorExecutionOk returns a tuple with the SaveDataErrorExecution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowSettings) GetSaveDataErrorExecutionOk() (*string, bool) {
	if o == nil || IsNil(o.SaveDataErrorExecution) {
		return nil, false
	}
	return o.SaveDataErrorExecution, true
}

// HasSaveDataErrorExecution returns a boolean if a field has been set.
func (o *WorkflowSettings) HasSaveDataErrorExecution() bool {
	if o != nil && !IsNil(o.SaveDataErrorExecution) {
		return true
	}

	return false
}

// SetSaveDataErrorExecution gets a reference to the given string and assigns it to the SaveDataErrorExecution field.
func (o *WorkflowSettings) SetSaveDataErrorExecution(v string) {
	o.SaveDataErrorExecution = &v
}

// GetSaveDataSuccessExecution returns the SaveDataSuccessExecution field value if set, zero value otherwise.
func (o *WorkflowSettings) GetSaveDataSuccessExecution() string {
	if o == nil || IsNil(o.SaveDataSuccessExecution) {
		var ret string
		return ret
	}
	return *o.SaveDataSuccessExecution
}

// GetSaveDataSuccessExecutionOk returns a tuple with the SaveDataSuccessExecution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowSettings) GetSaveDataSuccessExecutionOk() (*string, bool) {
	if o == nil || IsNil(o.SaveDataSuccessExecution) {
		return nil, false
	}
	return o.SaveDataSuccessExecution, true
}

// HasSaveDataSuccessExecution returns a boolean if a field has been set.
func (o *WorkflowSettings) HasSaveDataSuccessExecution() bool {
	if o != nil && !IsNil(o.SaveDataSuccessExecution) {
		return true
	}

	return false
}

// SetSaveDataSuccessExecution gets a reference to the given string and assigns it to the SaveDataSuccessExecution field.
func (o *WorkflowSettings) SetSaveDataSuccessExecution(v string) {
	o.SaveDataSuccessExecution = &v
}

// GetExecutionTimeout returns the ExecutionTimeout field value if set, zero value otherwise.
func (o *WorkflowSettings) GetExecutionTimeout() float32 {
	if o == nil || IsNil(o.ExecutionTimeout) {
		var ret float32
		return ret
	}
	return *o.ExecutionTimeout
}

// GetExecutionTimeoutOk returns a tuple with the ExecutionTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowSettings) GetExecutionTimeoutOk() (*float32, bool) {
	if o == nil || IsNil(o.ExecutionTimeout) {
		return nil, false
	}
	return o.ExecutionTimeout, true
}

// HasExecutionTimeout returns a boolean if a field has been set.
func (o *WorkflowSettings) HasExecutionTimeout() bool {
	if o != nil && !IsNil(o.ExecutionTimeout) {
		return true
	}

	return false
}

// SetExecutionTimeout gets a reference to the given float32 and assigns it to the ExecutionTimeout field.
func (o *WorkflowSettings) SetExecutionTimeout(v float32) {
	o.ExecutionTimeout = &v
}

// GetErrorWorkflow returns the ErrorWorkflow field value if set, zero value otherwise.
func (o *WorkflowSettings) GetErrorWorkflow() string {
	if o == nil || IsNil(o.ErrorWorkflow) {
		var ret string
		return ret
	}
	return *o.ErrorWorkflow
}

// GetErrorWorkflowOk returns a tuple with the ErrorWorkflow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowSettings) GetErrorWorkflowOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorWorkflow) {
		return nil, false
	}
	return o.ErrorWorkflow, true
}

// HasErrorWorkflow returns a boolean if a field has been set.
func (o *WorkflowSettings) HasErrorWorkflow() bool {
	if o != nil && !IsNil(o.ErrorWorkflow) {
		return true
	}

	return false
}

// SetErrorWorkflow gets a reference to the given string and assigns it to the ErrorWorkflow field.
func (o *WorkflowSettings) SetErrorWorkflow(v string) {
	o.ErrorWorkflow = &v
}

// GetTimezone returns the Timezone field value if set, zero value otherwise.
func (o *WorkflowSettings) GetTimezone() string {
	if o == nil || IsNil(o.Timezone) {
		var ret string
		return ret
	}
	return *o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowSettings) GetTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.Timezone) {
		return nil, false
	}
	return o.Timezone, true
}

// HasTimezone returns a boolean if a field has been set.
func (o *WorkflowSettings) HasTimezone() bool {
	if o != nil && !IsNil(o.Timezone) {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given string and assigns it to the Timezone field.
func (o *WorkflowSettings) SetTimezone(v string) {
	o.Timezone = &v
}

// GetExecutionOrder returns the ExecutionOrder field value if set, zero value otherwise.
func (o *WorkflowSettings) GetExecutionOrder() string {
	if o == nil || IsNil(o.ExecutionOrder) {
		var ret string
		return ret
	}
	return *o.ExecutionOrder
}

// GetExecutionOrderOk returns a tuple with the ExecutionOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowSettings) GetExecutionOrderOk() (*string, bool) {
	if o == nil || IsNil(o.ExecutionOrder) {
		return nil, false
	}
	return o.ExecutionOrder, true
}

// HasExecutionOrder returns a boolean if a field has been set.
func (o *WorkflowSettings) HasExecutionOrder() bool {
	if o != nil && !IsNil(o.ExecutionOrder) {
		return true
	}

	return false
}

// SetExecutionOrder gets a reference to the given string and assigns it to the ExecutionOrder field.
func (o *WorkflowSettings) SetExecutionOrder(v string) {
	o.ExecutionOrder = &v
}

// GetCallerPolicy returns the CallerPolicy field value if set, zero value otherwise.
func (o *WorkflowSettings) GetCallerPolicy() string {
	if o == nil || IsNil(o.CallerPolicy) {
		var ret string
		return ret
	}
	return *o.CallerPolicy
}

// GetCallerPolicyOk returns a tuple with the CallerPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowSettings) GetCallerPolicyOk() (*string, bool) {
	if o == nil || IsNil(o.CallerPolicy) {
		return nil, false
	}
	return o.CallerPolicy, true
}

// HasCallerPolicy returns a boolean if a field has been set.
func (o *WorkflowSettings) HasCallerPolicy() bool {
	if o != nil && !IsNil(o.CallerPolicy) {
		return true
	}

	return false
}

// SetCallerPolicy gets a reference to the given string and assigns it to the CallerPolicy field.
func (o *WorkflowSettings) SetCallerPolicy(v string) {
	o.CallerPolicy = &v
}

// GetCallerIds returns the CallerIds field value if set, zero value otherwise.
func (o *WorkflowSettings) GetCallerIds() string {
	if o == nil || IsNil(o.CallerIds) {
		var ret string
		return ret
	}
	return *o.CallerIds
}

// GetCallerIdsOk returns a tuple with the CallerIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowSettings) GetCallerIdsOk() (*string, bool) {
	if o == nil || IsNil(o.CallerIds) {
		return nil, false
	}
	return o.CallerIds, true
}

// HasCallerIds returns a boolean if a field has been set.
func (o *WorkflowSettings) HasCallerIds() bool {
	if o != nil && !IsNil(o.CallerIds) {
		return true
	}

	return false
}

// SetCallerIds gets a reference to the given string and assigns it to the CallerIds field.
func (o *WorkflowSettings) SetCallerIds(v string) {
	o.CallerIds = &v
}

// GetTimeSavedPerExecution returns the TimeSavedPerExecution field value if set, zero value otherwise.
func (o *WorkflowSettings) GetTimeSavedPerExecution() float32 {
	if o == nil || IsNil(o.TimeSavedPerExecution) {
		var ret float32
		return ret
	}
	return *o.TimeSavedPerExecution
}

// GetTimeSavedPerExecutionOk returns a tuple with the TimeSavedPerExecution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowSettings) GetTimeSavedPerExecutionOk() (*float32, bool) {
	if o == nil || IsNil(o.TimeSavedPerExecution) {
		return nil, false
	}
	return o.TimeSavedPerExecution, true
}

// HasTimeSavedPerExecution returns a boolean if a field has been set.
func (o *WorkflowSettings) HasTimeSavedPerExecution() bool {
	if o != nil && !IsNil(o.TimeSavedPerExecution) {
		return true
	}

	return false
}

// SetTimeSavedPerExecution gets a reference to the given float32 and assigns it to the TimeSavedPerExecution field.
func (o *WorkflowSettings) SetTimeSavedPerExecution(v float32) {
	o.TimeSavedPerExecution = &v
}

// GetAvailableInMCP returns the AvailableInMCP field value if set, zero value otherwise.
func (o *WorkflowSettings) GetAvailableInMCP() bool {
	if o == nil || IsNil(o.AvailableInMCP) {
		var ret bool
		return ret
	}
	return *o.AvailableInMCP
}

// GetAvailableInMCPOk returns a tuple with the AvailableInMCP field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowSettings) GetAvailableInMCPOk() (*bool, bool) {
	if o == nil || IsNil(o.AvailableInMCP) {
		return nil, false
	}
	return o.AvailableInMCP, true
}

// HasAvailableInMCP returns a boolean if a field has been set.
func (o *WorkflowSettings) HasAvailableInMCP() bool {
	if o != nil && !IsNil(o.AvailableInMCP) {
		return true
	}

	return false
}

// SetAvailableInMCP gets a reference to the given bool and assigns it to the AvailableInMCP field.
func (o *WorkflowSettings) SetAvailableInMCP(v bool) {
	o.AvailableInMCP = &v
}

func (o WorkflowSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SaveExecutionProgress) {
		toSerialize["saveExecutionProgress"] = o.SaveExecutionProgress
	}
	if !IsNil(o.SaveManualExecutions) {
		toSerialize["saveManualExecutions"] = o.SaveManualExecutions
	}
	if !IsNil(o.SaveDataErrorExecution) {
		toSerialize["saveDataErrorExecution"] = o.SaveDataErrorExecution
	}
	if !IsNil(o.SaveDataSuccessExecution) {
		toSerialize["saveDataSuccessExecution"] = o.SaveDataSuccessExecution
	}
	if !IsNil(o.ExecutionTimeout) {
		toSerialize["executionTimeout"] = o.ExecutionTimeout
	}
	if !IsNil(o.ErrorWorkflow) {
		toSerialize["errorWorkflow"] = o.ErrorWorkflow
	}
	if !IsNil(o.Timezone) {
		toSerialize["timezone"] = o.Timezone
	}
	if !IsNil(o.ExecutionOrder) {
		toSerialize["executionOrder"] = o.ExecutionOrder
	}
	if !IsNil(o.CallerPolicy) {
		toSerialize["callerPolicy"] = o.CallerPolicy
	}
	if !IsNil(o.CallerIds) {
		toSerialize["callerIds"] = o.CallerIds
	}
	if !IsNil(o.TimeSavedPerExecution) {
		toSerialize["timeSavedPerExecution"] = o.TimeSavedPerExecution
	}
	if !IsNil(o.AvailableInMCP) {
		toSerialize["availableInMCP"] = o.AvailableInMCP
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WorkflowSettings) UnmarshalJSON(data []byte) (err error) {
	varWorkflowSettings := _WorkflowSettings{}

	err = json.Unmarshal(data, &varWorkflowSettings)

	if err != nil {
		return err
	}

	*o = WorkflowSettings(varWorkflowSettings)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "saveExecutionProgress")
		delete(additionalProperties, "saveManualExecutions")
		delete(additionalProperties, "saveDataErrorExecution")
		delete(additionalProperties, "saveDataSuccessExecution")
		delete(additionalProperties, "executionTimeout")
		delete(additionalProperties, "errorWorkflow")
		delete(additionalProperties, "timezone")
		delete(additionalProperties, "executionOrder")
		delete(additionalProperties, "callerPolicy")
		delete(additionalProperties, "callerIds")
		delete(additionalProperties, "timeSavedPerExecution")
		delete(additionalProperties, "availableInMCP")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWorkflowSettings struct {
	value *WorkflowSettings
	isSet bool
}

func (v NullableWorkflowSettings) Get() *WorkflowSettings {
	return v.value
}

func (v *NullableWorkflowSettings) Set(val *WorkflowSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowSettings(val *WorkflowSettings) *NullableWorkflowSettings {
	return &NullableWorkflowSettings{value: val, isSet: true}
}

func (v NullableWorkflowSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
