/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
)

// checks if the UsersPost201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersPost201Response{}

// UsersPost201Response struct for UsersPost201Response
type UsersPost201Response struct {
	User *UsersPost201ResponseUser `json:"user,omitempty"`
	Error *string `json:"error,omitempty"`
}

// NewUsersPost201Response instantiates a new UsersPost201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersPost201Response() *UsersPost201Response {
	this := UsersPost201Response{}
	return &this
}

// NewUsersPost201ResponseWithDefaults instantiates a new UsersPost201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersPost201ResponseWithDefaults() *UsersPost201Response {
	this := UsersPost201Response{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *UsersPost201Response) GetUser() UsersPost201ResponseUser {
	if o == nil || IsNil(o.User) {
		var ret UsersPost201ResponseUser
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersPost201Response) GetUserOk() (*UsersPost201ResponseUser, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *UsersPost201Response) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given UsersPost201ResponseUser and assigns it to the User field.
func (o *UsersPost201Response) SetUser(v UsersPost201ResponseUser) {
	o.User = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *UsersPost201Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersPost201Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *UsersPost201Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *UsersPost201Response) SetError(v string) {
	o.Error = &v
}

func (o UsersPost201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersPost201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableUsersPost201Response struct {
	value *UsersPost201Response
	isSet bool
}

func (v NullableUsersPost201Response) Get() *UsersPost201Response {
	return v.value
}

func (v *NullableUsersPost201Response) Set(val *UsersPost201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersPost201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersPost201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersPost201Response(val *UsersPost201Response) *NullableUsersPost201Response {
	return &NullableUsersPost201Response{value: val, isSet: true}
}

func (v NullableUsersPost201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersPost201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


