/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the DataTable type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataTable{}

// DataTable struct for DataTable
type DataTable struct {
	// Unique identifier for the data table
	Id string `json:"id"`
	// Name of the data table
	Name string `json:"name"`
	// Column definitions
	Columns []DataTableColumnsInner `json:"columns"`
	// ID of the project this table belongs to
	ProjectId string `json:"projectId"`
	// Timestamp when the table was created
	CreatedAt time.Time `json:"createdAt"`
	// Timestamp when the table was last updated
	UpdatedAt            time.Time `json:"updatedAt"`
	AdditionalProperties map[string]interface{}
}

type _DataTable DataTable

// NewDataTable instantiates a new DataTable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataTable(id string, name string, columns []DataTableColumnsInner, projectId string, createdAt time.Time, updatedAt time.Time) *DataTable {
	this := DataTable{}
	this.Id = id
	this.Name = name
	this.Columns = columns
	this.ProjectId = projectId
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewDataTableWithDefaults instantiates a new DataTable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataTableWithDefaults() *DataTable {
	this := DataTable{}
	return &this
}

// GetId returns the Id field value
func (o *DataTable) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DataTable) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DataTable) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *DataTable) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DataTable) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DataTable) SetName(v string) {
	o.Name = v
}

// GetColumns returns the Columns field value
func (o *DataTable) GetColumns() []DataTableColumnsInner {
	if o == nil {
		var ret []DataTableColumnsInner
		return ret
	}

	return o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value
// and a boolean to check if the value has been set.
func (o *DataTable) GetColumnsOk() ([]DataTableColumnsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Columns, true
}

// SetColumns sets field value
func (o *DataTable) SetColumns(v []DataTableColumnsInner) {
	o.Columns = v
}

// GetProjectId returns the ProjectId field value
func (o *DataTable) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *DataTable) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *DataTable) SetProjectId(v string) {
	o.ProjectId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *DataTable) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *DataTable) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *DataTable) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *DataTable) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *DataTable) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *DataTable) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o DataTable) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataTable) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["columns"] = o.Columns
	toSerialize["projectId"] = o.ProjectId
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DataTable) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"columns",
		"projectId",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataTable := _DataTable{}

	err = json.Unmarshal(data, &varDataTable)

	if err != nil {
		return err
	}

	*o = DataTable(varDataTable)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "columns")
		delete(additionalProperties, "projectId")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDataTable struct {
	value *DataTable
	isSet bool
}

func (v NullableDataTable) Get() *DataTable {
	return v.value
}

func (v *NullableDataTable) Set(val *DataTable) {
	v.value = val
	v.isSet = true
}

func (v NullableDataTable) IsSet() bool {
	return v.isSet
}

func (v *NullableDataTable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataTable(val *DataTable) *NullableDataTable {
	return &NullableDataTable{value: val, isSet: true}
}

func (v NullableDataTable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataTable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
