/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
)

// checks if the Audit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Audit{}

// Audit struct for Audit
type Audit struct {
	CredentialsRiskReport map[string]interface{} `json:"Credentials Risk Report,omitempty"`
	DatabaseRiskReport map[string]interface{} `json:"Database Risk Report,omitempty"`
	FilesystemRiskReport map[string]interface{} `json:"Filesystem Risk Report,omitempty"`
	NodesRiskReport map[string]interface{} `json:"Nodes Risk Report,omitempty"`
	InstanceRiskReport map[string]interface{} `json:"Instance Risk Report,omitempty"`
}

// NewAudit instantiates a new Audit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAudit() *Audit {
	this := Audit{}
	return &this
}

// NewAuditWithDefaults instantiates a new Audit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuditWithDefaults() *Audit {
	this := Audit{}
	return &this
}

// GetCredentialsRiskReport returns the CredentialsRiskReport field value if set, zero value otherwise.
func (o *Audit) GetCredentialsRiskReport() map[string]interface{} {
	if o == nil || IsNil(o.CredentialsRiskReport) {
		var ret map[string]interface{}
		return ret
	}
	return o.CredentialsRiskReport
}

// GetCredentialsRiskReportOk returns a tuple with the CredentialsRiskReport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Audit) GetCredentialsRiskReportOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CredentialsRiskReport) {
		return map[string]interface{}{}, false
	}
	return o.CredentialsRiskReport, true
}

// HasCredentialsRiskReport returns a boolean if a field has been set.
func (o *Audit) HasCredentialsRiskReport() bool {
	if o != nil && !IsNil(o.CredentialsRiskReport) {
		return true
	}

	return false
}

// SetCredentialsRiskReport gets a reference to the given map[string]interface{} and assigns it to the CredentialsRiskReport field.
func (o *Audit) SetCredentialsRiskReport(v map[string]interface{}) {
	o.CredentialsRiskReport = v
}

// GetDatabaseRiskReport returns the DatabaseRiskReport field value if set, zero value otherwise.
func (o *Audit) GetDatabaseRiskReport() map[string]interface{} {
	if o == nil || IsNil(o.DatabaseRiskReport) {
		var ret map[string]interface{}
		return ret
	}
	return o.DatabaseRiskReport
}

// GetDatabaseRiskReportOk returns a tuple with the DatabaseRiskReport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Audit) GetDatabaseRiskReportOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.DatabaseRiskReport) {
		return map[string]interface{}{}, false
	}
	return o.DatabaseRiskReport, true
}

// HasDatabaseRiskReport returns a boolean if a field has been set.
func (o *Audit) HasDatabaseRiskReport() bool {
	if o != nil && !IsNil(o.DatabaseRiskReport) {
		return true
	}

	return false
}

// SetDatabaseRiskReport gets a reference to the given map[string]interface{} and assigns it to the DatabaseRiskReport field.
func (o *Audit) SetDatabaseRiskReport(v map[string]interface{}) {
	o.DatabaseRiskReport = v
}

// GetFilesystemRiskReport returns the FilesystemRiskReport field value if set, zero value otherwise.
func (o *Audit) GetFilesystemRiskReport() map[string]interface{} {
	if o == nil || IsNil(o.FilesystemRiskReport) {
		var ret map[string]interface{}
		return ret
	}
	return o.FilesystemRiskReport
}

// GetFilesystemRiskReportOk returns a tuple with the FilesystemRiskReport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Audit) GetFilesystemRiskReportOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.FilesystemRiskReport) {
		return map[string]interface{}{}, false
	}
	return o.FilesystemRiskReport, true
}

// HasFilesystemRiskReport returns a boolean if a field has been set.
func (o *Audit) HasFilesystemRiskReport() bool {
	if o != nil && !IsNil(o.FilesystemRiskReport) {
		return true
	}

	return false
}

// SetFilesystemRiskReport gets a reference to the given map[string]interface{} and assigns it to the FilesystemRiskReport field.
func (o *Audit) SetFilesystemRiskReport(v map[string]interface{}) {
	o.FilesystemRiskReport = v
}

// GetNodesRiskReport returns the NodesRiskReport field value if set, zero value otherwise.
func (o *Audit) GetNodesRiskReport() map[string]interface{} {
	if o == nil || IsNil(o.NodesRiskReport) {
		var ret map[string]interface{}
		return ret
	}
	return o.NodesRiskReport
}

// GetNodesRiskReportOk returns a tuple with the NodesRiskReport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Audit) GetNodesRiskReportOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.NodesRiskReport) {
		return map[string]interface{}{}, false
	}
	return o.NodesRiskReport, true
}

// HasNodesRiskReport returns a boolean if a field has been set.
func (o *Audit) HasNodesRiskReport() bool {
	if o != nil && !IsNil(o.NodesRiskReport) {
		return true
	}

	return false
}

// SetNodesRiskReport gets a reference to the given map[string]interface{} and assigns it to the NodesRiskReport field.
func (o *Audit) SetNodesRiskReport(v map[string]interface{}) {
	o.NodesRiskReport = v
}

// GetInstanceRiskReport returns the InstanceRiskReport field value if set, zero value otherwise.
func (o *Audit) GetInstanceRiskReport() map[string]interface{} {
	if o == nil || IsNil(o.InstanceRiskReport) {
		var ret map[string]interface{}
		return ret
	}
	return o.InstanceRiskReport
}

// GetInstanceRiskReportOk returns a tuple with the InstanceRiskReport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Audit) GetInstanceRiskReportOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.InstanceRiskReport) {
		return map[string]interface{}{}, false
	}
	return o.InstanceRiskReport, true
}

// HasInstanceRiskReport returns a boolean if a field has been set.
func (o *Audit) HasInstanceRiskReport() bool {
	if o != nil && !IsNil(o.InstanceRiskReport) {
		return true
	}

	return false
}

// SetInstanceRiskReport gets a reference to the given map[string]interface{} and assigns it to the InstanceRiskReport field.
func (o *Audit) SetInstanceRiskReport(v map[string]interface{}) {
	o.InstanceRiskReport = v
}

func (o Audit) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Audit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CredentialsRiskReport) {
		toSerialize["Credentials Risk Report"] = o.CredentialsRiskReport
	}
	if !IsNil(o.DatabaseRiskReport) {
		toSerialize["Database Risk Report"] = o.DatabaseRiskReport
	}
	if !IsNil(o.FilesystemRiskReport) {
		toSerialize["Filesystem Risk Report"] = o.FilesystemRiskReport
	}
	if !IsNil(o.NodesRiskReport) {
		toSerialize["Nodes Risk Report"] = o.NodesRiskReport
	}
	if !IsNil(o.InstanceRiskReport) {
		toSerialize["Instance Risk Report"] = o.InstanceRiskReport
	}
	return toSerialize, nil
}

type NullableAudit struct {
	value *Audit
	isSet bool
}

func (v NullableAudit) Get() *Audit {
	return v.value
}

func (v *NullableAudit) Set(val *Audit) {
	v.value = val
	v.isSet = true
}

func (v NullableAudit) IsSet() bool {
	return v.isSet
}

func (v *NullableAudit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAudit(val *Audit) *NullableAudit {
	return &NullableAudit{value: val, isSet: true}
}

func (v NullableAudit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAudit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


