/*
n8n Public API

n8n Public API

API version: 2.0.0
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"time"
)

// CredentialSharedItem represents a project sharing entry for a credential.
type CredentialSharedItem struct {
	// Project ID.
	ID string `json:"id"`
	// Project name.
	Name string `json:"name"`
	// Role of the credential in this project.
	Role string `json:"role"`
	// When the credential was shared with this project.
	CreatedAt time.Time `json:"createdAt"`
	// When the sharing was last updated.
	UpdatedAt time.Time `json:"updatedAt"`
}

// CredentialListItem represents a credential in a list response (no secret data).
type CredentialListItem struct {
	// Credential identifier.
	ID string `json:"id"`
	// Credential name.
	Name string `json:"name"`
	// Credential type.
	Type string `json:"type"`
	// When the credential was created.
	CreatedAt time.Time `json:"createdAt"`
	// When the credential was last updated.
	UpdatedAt time.Time `json:"updatedAt"`
	// Shared entries from the credential's shared relation.
	Shared []CredentialSharedItem `json:"shared,omitempty"`
}

// CredentialList is the response for listing credentials.
type CredentialList struct {
	// List of credentials.
	Data []CredentialListItem `json:"data,omitempty"`
	// Cursor for pagination.
	NextCursor *string `json:"nextCursor,omitempty"`
}
