/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
)

// checks if the DataTableColumnsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataTableColumnsInner{}

// DataTableColumnsInner struct for DataTableColumnsInner
type DataTableColumnsInner struct {
	// Column ID
	Id *string `json:"id,omitempty"`
	// Column name
	Name *string `json:"name,omitempty"`
	// Column data type
	Type *string `json:"type,omitempty"`
	// Column position
	Index                *int32 `json:"index,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DataTableColumnsInner DataTableColumnsInner

// NewDataTableColumnsInner instantiates a new DataTableColumnsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataTableColumnsInner() *DataTableColumnsInner {
	this := DataTableColumnsInner{}
	return &this
}

// NewDataTableColumnsInnerWithDefaults instantiates a new DataTableColumnsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataTableColumnsInnerWithDefaults() *DataTableColumnsInner {
	this := DataTableColumnsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DataTableColumnsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataTableColumnsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DataTableColumnsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DataTableColumnsInner) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DataTableColumnsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataTableColumnsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DataTableColumnsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DataTableColumnsInner) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *DataTableColumnsInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataTableColumnsInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *DataTableColumnsInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *DataTableColumnsInner) SetType(v string) {
	o.Type = &v
}

// GetIndex returns the Index field value if set, zero value otherwise.
func (o *DataTableColumnsInner) GetIndex() int32 {
	if o == nil || IsNil(o.Index) {
		var ret int32
		return ret
	}
	return *o.Index
}

// GetIndexOk returns a tuple with the Index field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataTableColumnsInner) GetIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.Index) {
		return nil, false
	}
	return o.Index, true
}

// HasIndex returns a boolean if a field has been set.
func (o *DataTableColumnsInner) HasIndex() bool {
	if o != nil && !IsNil(o.Index) {
		return true
	}

	return false
}

// SetIndex gets a reference to the given int32 and assigns it to the Index field.
func (o *DataTableColumnsInner) SetIndex(v int32) {
	o.Index = &v
}

func (o DataTableColumnsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataTableColumnsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Index) {
		toSerialize["index"] = o.Index
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DataTableColumnsInner) UnmarshalJSON(data []byte) (err error) {
	varDataTableColumnsInner := _DataTableColumnsInner{}

	err = json.Unmarshal(data, &varDataTableColumnsInner)

	if err != nil {
		return err
	}

	*o = DataTableColumnsInner(varDataTableColumnsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "type")
		delete(additionalProperties, "index")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDataTableColumnsInner struct {
	value *DataTableColumnsInner
	isSet bool
}

func (v NullableDataTableColumnsInner) Get() *DataTableColumnsInner {
	return v.value
}

func (v *NullableDataTableColumnsInner) Set(val *DataTableColumnsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableDataTableColumnsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableDataTableColumnsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataTableColumnsInner(val *DataTableColumnsInner) *NullableDataTableColumnsInner {
	return &NullableDataTableColumnsInner{value: val, isSet: true}
}

func (v NullableDataTableColumnsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataTableColumnsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
