/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateDataTableRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDataTableRequest{}

// CreateDataTableRequest struct for CreateDataTableRequest
type CreateDataTableRequest struct {
	// Name of the data table
	Name string `json:"name"`
	// Column definitions for the table
	Columns              []CreateDataTableRequestColumnsInner `json:"columns"`
	AdditionalProperties map[string]interface{}
}

type _CreateDataTableRequest CreateDataTableRequest

// NewCreateDataTableRequest instantiates a new CreateDataTableRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDataTableRequest(name string, columns []CreateDataTableRequestColumnsInner) *CreateDataTableRequest {
	this := CreateDataTableRequest{}
	this.Name = name
	this.Columns = columns
	return &this
}

// NewCreateDataTableRequestWithDefaults instantiates a new CreateDataTableRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDataTableRequestWithDefaults() *CreateDataTableRequest {
	this := CreateDataTableRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateDataTableRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateDataTableRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateDataTableRequest) SetName(v string) {
	o.Name = v
}

// GetColumns returns the Columns field value
func (o *CreateDataTableRequest) GetColumns() []CreateDataTableRequestColumnsInner {
	if o == nil {
		var ret []CreateDataTableRequestColumnsInner
		return ret
	}

	return o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value
// and a boolean to check if the value has been set.
func (o *CreateDataTableRequest) GetColumnsOk() ([]CreateDataTableRequestColumnsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Columns, true
}

// SetColumns sets field value
func (o *CreateDataTableRequest) SetColumns(v []CreateDataTableRequestColumnsInner) {
	o.Columns = v
}

func (o CreateDataTableRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDataTableRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["columns"] = o.Columns

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateDataTableRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"columns",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDataTableRequest := _CreateDataTableRequest{}

	err = json.Unmarshal(data, &varCreateDataTableRequest)

	if err != nil {
		return err
	}

	*o = CreateDataTableRequest(varCreateDataTableRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "columns")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateDataTableRequest struct {
	value *CreateDataTableRequest
	isSet bool
}

func (v NullableCreateDataTableRequest) Get() *CreateDataTableRequest {
	return v.value
}

func (v *NullableCreateDataTableRequest) Set(val *CreateDataTableRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDataTableRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDataTableRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDataTableRequest(val *CreateDataTableRequest) *NullableCreateDataTableRequest {
	return &NullableCreateDataTableRequest{value: val, isSet: true}
}

func (v NullableCreateDataTableRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDataTableRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
