/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateRowsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateRowsRequest{}

// UpdateRowsRequest struct for UpdateRowsRequest
type UpdateRowsRequest struct {
	Filter UpdateRowsRequestFilter `json:"filter"`
	// Column values to update
	Data map[string]interface{} `json:"data"`
	// If true, return the updated rows; if false, return true on success
	ReturnData *bool `json:"returnData,omitempty"`
	// If true, preview changes without persisting them
	DryRun               *bool `json:"dryRun,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateRowsRequest UpdateRowsRequest

// NewUpdateRowsRequest instantiates a new UpdateRowsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateRowsRequest(filter UpdateRowsRequestFilter, data map[string]interface{}) *UpdateRowsRequest {
	this := UpdateRowsRequest{}
	this.Filter = filter
	this.Data = data
	var returnData bool = false
	this.ReturnData = &returnData
	var dryRun bool = false
	this.DryRun = &dryRun
	return &this
}

// NewUpdateRowsRequestWithDefaults instantiates a new UpdateRowsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateRowsRequestWithDefaults() *UpdateRowsRequest {
	this := UpdateRowsRequest{}
	var returnData bool = false
	this.ReturnData = &returnData
	var dryRun bool = false
	this.DryRun = &dryRun
	return &this
}

// GetFilter returns the Filter field value
func (o *UpdateRowsRequest) GetFilter() UpdateRowsRequestFilter {
	if o == nil {
		var ret UpdateRowsRequestFilter
		return ret
	}

	return o.Filter
}

// GetFilterOk returns a tuple with the Filter field value
// and a boolean to check if the value has been set.
func (o *UpdateRowsRequest) GetFilterOk() (*UpdateRowsRequestFilter, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filter, true
}

// SetFilter sets field value
func (o *UpdateRowsRequest) SetFilter(v UpdateRowsRequestFilter) {
	o.Filter = v
}

// GetData returns the Data field value
func (o *UpdateRowsRequest) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateRowsRequest) GetDataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *UpdateRowsRequest) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetReturnData returns the ReturnData field value if set, zero value otherwise.
func (o *UpdateRowsRequest) GetReturnData() bool {
	if o == nil || IsNil(o.ReturnData) {
		var ret bool
		return ret
	}
	return *o.ReturnData
}

// GetReturnDataOk returns a tuple with the ReturnData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRowsRequest) GetReturnDataOk() (*bool, bool) {
	if o == nil || IsNil(o.ReturnData) {
		return nil, false
	}
	return o.ReturnData, true
}

// HasReturnData returns a boolean if a field has been set.
func (o *UpdateRowsRequest) HasReturnData() bool {
	if o != nil && !IsNil(o.ReturnData) {
		return true
	}

	return false
}

// SetReturnData gets a reference to the given bool and assigns it to the ReturnData field.
func (o *UpdateRowsRequest) SetReturnData(v bool) {
	o.ReturnData = &v
}

// GetDryRun returns the DryRun field value if set, zero value otherwise.
func (o *UpdateRowsRequest) GetDryRun() bool {
	if o == nil || IsNil(o.DryRun) {
		var ret bool
		return ret
	}
	return *o.DryRun
}

// GetDryRunOk returns a tuple with the DryRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateRowsRequest) GetDryRunOk() (*bool, bool) {
	if o == nil || IsNil(o.DryRun) {
		return nil, false
	}
	return o.DryRun, true
}

// HasDryRun returns a boolean if a field has been set.
func (o *UpdateRowsRequest) HasDryRun() bool {
	if o != nil && !IsNil(o.DryRun) {
		return true
	}

	return false
}

// SetDryRun gets a reference to the given bool and assigns it to the DryRun field.
func (o *UpdateRowsRequest) SetDryRun(v bool) {
	o.DryRun = &v
}

func (o UpdateRowsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateRowsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["filter"] = o.Filter
	toSerialize["data"] = o.Data
	if !IsNil(o.ReturnData) {
		toSerialize["returnData"] = o.ReturnData
	}
	if !IsNil(o.DryRun) {
		toSerialize["dryRun"] = o.DryRun
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateRowsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"filter",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateRowsRequest := _UpdateRowsRequest{}

	err = json.Unmarshal(data, &varUpdateRowsRequest)

	if err != nil {
		return err
	}

	*o = UpdateRowsRequest(varUpdateRowsRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "filter")
		delete(additionalProperties, "data")
		delete(additionalProperties, "returnData")
		delete(additionalProperties, "dryRun")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateRowsRequest struct {
	value *UpdateRowsRequest
	isSet bool
}

func (v NullableUpdateRowsRequest) Get() *UpdateRowsRequest {
	return v.value
}

func (v *NullableUpdateRowsRequest) Set(val *UpdateRowsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateRowsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateRowsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateRowsRequest(val *UpdateRowsRequest) *NullableUpdateRowsRequest {
	return &NullableUpdateRowsRequest{value: val, isSet: true}
}

func (v NullableUpdateRowsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateRowsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
