/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
	"time"
)

// checks if the SharedWorkflow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SharedWorkflow{}

// SharedWorkflow struct for SharedWorkflow
type SharedWorkflow struct {
	// Shared workflow ID
	Id *string `json:"id,omitempty"`
	// Project ID
	ProjectId *string `json:"projectId,omitempty"`
	// User ID
	UserId *string `json:"userId,omitempty"`
	// User role
	Role                 *string                 `json:"role,omitempty"`
	WorkflowId           *string                 `json:"workflowId,omitempty"`
	Project              *SharedWorkflowProject1 `json:"project,omitempty"`
	CreatedAt            *time.Time              `json:"createdAt,omitempty"`
	UpdatedAt            *time.Time              `json:"updatedAt,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SharedWorkflow SharedWorkflow

// NewSharedWorkflow instantiates a new SharedWorkflow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSharedWorkflow() *SharedWorkflow {
	this := SharedWorkflow{}
	return &this
}

// NewSharedWorkflowWithDefaults instantiates a new SharedWorkflow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSharedWorkflowWithDefaults() *SharedWorkflow {
	this := SharedWorkflow{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SharedWorkflow) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SharedWorkflow) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SharedWorkflow) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SharedWorkflow) SetId(v string) {
	o.Id = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *SharedWorkflow) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SharedWorkflow) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *SharedWorkflow) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *SharedWorkflow) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *SharedWorkflow) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SharedWorkflow) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *SharedWorkflow) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *SharedWorkflow) SetUserId(v string) {
	o.UserId = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *SharedWorkflow) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SharedWorkflow) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *SharedWorkflow) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *SharedWorkflow) SetRole(v string) {
	o.Role = &v
}

// GetWorkflowId returns the WorkflowId field value if set, zero value otherwise.
func (o *SharedWorkflow) GetWorkflowId() string {
	if o == nil || IsNil(o.WorkflowId) {
		var ret string
		return ret
	}
	return *o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SharedWorkflow) GetWorkflowIdOk() (*string, bool) {
	if o == nil || IsNil(o.WorkflowId) {
		return nil, false
	}
	return o.WorkflowId, true
}

// HasWorkflowId returns a boolean if a field has been set.
func (o *SharedWorkflow) HasWorkflowId() bool {
	if o != nil && !IsNil(o.WorkflowId) {
		return true
	}

	return false
}

// SetWorkflowId gets a reference to the given string and assigns it to the WorkflowId field.
func (o *SharedWorkflow) SetWorkflowId(v string) {
	o.WorkflowId = &v
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *SharedWorkflow) GetProject() SharedWorkflowProject1 {
	if o == nil || IsNil(o.Project) {
		var ret SharedWorkflowProject1
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SharedWorkflow) GetProjectOk() (*SharedWorkflowProject1, bool) {
	if o == nil || IsNil(o.Project) {
		return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *SharedWorkflow) HasProject() bool {
	if o != nil && !IsNil(o.Project) {
		return true
	}

	return false
}

// SetProject gets a reference to the given SharedWorkflowProject1 and assigns it to the Project field.
func (o *SharedWorkflow) SetProject(v SharedWorkflowProject1) {
	o.Project = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *SharedWorkflow) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SharedWorkflow) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *SharedWorkflow) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *SharedWorkflow) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *SharedWorkflow) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SharedWorkflow) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *SharedWorkflow) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *SharedWorkflow) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o SharedWorkflow) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SharedWorkflow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ProjectId) {
		toSerialize["projectId"] = o.ProjectId
	}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.WorkflowId) {
		toSerialize["workflowId"] = o.WorkflowId
	}
	if !IsNil(o.Project) {
		toSerialize["project"] = o.Project
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SharedWorkflow) UnmarshalJSON(data []byte) (err error) {
	varSharedWorkflow := _SharedWorkflow{}

	err = json.Unmarshal(data, &varSharedWorkflow)

	if err != nil {
		return err
	}

	*o = SharedWorkflow(varSharedWorkflow)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "projectId")
		delete(additionalProperties, "userId")
		delete(additionalProperties, "role")
		delete(additionalProperties, "workflowId")
		delete(additionalProperties, "project")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSharedWorkflow struct {
	value *SharedWorkflow
	isSet bool
}

func (v NullableSharedWorkflow) Get() *SharedWorkflow {
	return v.value
}

func (v *NullableSharedWorkflow) Set(val *SharedWorkflow) {
	v.value = val
	v.isSet = true
}

func (v NullableSharedWorkflow) IsSet() bool {
	return v.isSet
}

func (v *NullableSharedWorkflow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSharedWorkflow(val *SharedWorkflow) *NullableSharedWorkflow {
	return &NullableSharedWorkflow{value: val, isSet: true}
}

func (v NullableSharedWorkflow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSharedWorkflow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
