/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the WorkflowVersion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowVersion{}

// WorkflowVersion struct for WorkflowVersion
type WorkflowVersion struct {
	// The version ID of this workflow snapshot
	VersionId string `json:"versionId"`
	// The workflow ID this version belongs to
	WorkflowId string `json:"workflowId"`
	// Nodes as they were in this version
	Nodes []Node `json:"nodes"`
	// Connections as they were in this version
	Connections map[string]interface{} `json:"connections"`
	// Authors who created this version
	Authors string `json:"authors"`
	// Workflow name at this version
	Name NullableString `json:"name,omitempty"`
	// Workflow description at this version
	Description NullableString `json:"description,omitempty"`
	// When this version was created
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// When this version was last updated
	UpdatedAt            *time.Time `json:"updatedAt,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WorkflowVersion WorkflowVersion

// NewWorkflowVersion instantiates a new WorkflowVersion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowVersion(versionId string, workflowId string, nodes []Node, connections map[string]interface{}, authors string) *WorkflowVersion {
	this := WorkflowVersion{}
	this.VersionId = versionId
	this.WorkflowId = workflowId
	this.Nodes = nodes
	this.Connections = connections
	this.Authors = authors
	return &this
}

// NewWorkflowVersionWithDefaults instantiates a new WorkflowVersion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowVersionWithDefaults() *WorkflowVersion {
	this := WorkflowVersion{}
	return &this
}

// GetVersionId returns the VersionId field value
func (o *WorkflowVersion) GetVersionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value
// and a boolean to check if the value has been set.
func (o *WorkflowVersion) GetVersionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VersionId, true
}

// SetVersionId sets field value
func (o *WorkflowVersion) SetVersionId(v string) {
	o.VersionId = v
}

// GetWorkflowId returns the WorkflowId field value
func (o *WorkflowVersion) GetWorkflowId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value
// and a boolean to check if the value has been set.
func (o *WorkflowVersion) GetWorkflowIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowId, true
}

// SetWorkflowId sets field value
func (o *WorkflowVersion) SetWorkflowId(v string) {
	o.WorkflowId = v
}

// GetNodes returns the Nodes field value
func (o *WorkflowVersion) GetNodes() []Node {
	if o == nil {
		var ret []Node
		return ret
	}

	return o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value
// and a boolean to check if the value has been set.
func (o *WorkflowVersion) GetNodesOk() ([]Node, bool) {
	if o == nil {
		return nil, false
	}
	return o.Nodes, true
}

// SetNodes sets field value
func (o *WorkflowVersion) SetNodes(v []Node) {
	o.Nodes = v
}

// GetConnections returns the Connections field value
func (o *WorkflowVersion) GetConnections() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Connections
}

// GetConnectionsOk returns a tuple with the Connections field value
// and a boolean to check if the value has been set.
func (o *WorkflowVersion) GetConnectionsOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Connections, true
}

// SetConnections sets field value
func (o *WorkflowVersion) SetConnections(v map[string]interface{}) {
	o.Connections = v
}

// GetAuthors returns the Authors field value
func (o *WorkflowVersion) GetAuthors() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Authors
}

// GetAuthorsOk returns a tuple with the Authors field value
// and a boolean to check if the value has been set.
func (o *WorkflowVersion) GetAuthorsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Authors, true
}

// SetAuthors sets field value
func (o *WorkflowVersion) SetAuthors(v string) {
	o.Authors = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowVersion) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowVersion) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *WorkflowVersion) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *WorkflowVersion) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *WorkflowVersion) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *WorkflowVersion) UnsetName() {
	o.Name.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowVersion) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowVersion) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *WorkflowVersion) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *WorkflowVersion) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *WorkflowVersion) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *WorkflowVersion) UnsetDescription() {
	o.Description.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *WorkflowVersion) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowVersion) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *WorkflowVersion) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *WorkflowVersion) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *WorkflowVersion) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowVersion) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *WorkflowVersion) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *WorkflowVersion) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o WorkflowVersion) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowVersion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["versionId"] = o.VersionId
	toSerialize["workflowId"] = o.WorkflowId
	toSerialize["nodes"] = o.Nodes
	toSerialize["connections"] = o.Connections
	toSerialize["authors"] = o.Authors
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WorkflowVersion) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"versionId",
		"workflowId",
		"nodes",
		"connections",
		"authors",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowVersion := _WorkflowVersion{}

	err = json.Unmarshal(data, &varWorkflowVersion)

	if err != nil {
		return err
	}

	*o = WorkflowVersion(varWorkflowVersion)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "versionId")
		delete(additionalProperties, "workflowId")
		delete(additionalProperties, "nodes")
		delete(additionalProperties, "connections")
		delete(additionalProperties, "authors")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWorkflowVersion struct {
	value *WorkflowVersion
	isSet bool
}

func (v NullableWorkflowVersion) Get() *WorkflowVersion {
	return v.value
}

func (v *NullableWorkflowVersion) Set(val *WorkflowVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowVersion(val *WorkflowVersion) *NullableWorkflowVersion {
	return &NullableWorkflowVersion{value: val, isSet: true}
}

func (v NullableWorkflowVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
