/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the WorkflowsIdTransferPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowsIdTransferPutRequest{}

// WorkflowsIdTransferPutRequest struct for WorkflowsIdTransferPutRequest
type WorkflowsIdTransferPutRequest struct {
	// The ID of the project to transfer the workflow to.
	DestinationProjectId string `json:"destinationProjectId"`
	AdditionalProperties map[string]interface{}
}

type _WorkflowsIdTransferPutRequest WorkflowsIdTransferPutRequest

// NewWorkflowsIdTransferPutRequest instantiates a new WorkflowsIdTransferPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowsIdTransferPutRequest(destinationProjectId string) *WorkflowsIdTransferPutRequest {
	this := WorkflowsIdTransferPutRequest{}
	this.DestinationProjectId = destinationProjectId
	return &this
}

// NewWorkflowsIdTransferPutRequestWithDefaults instantiates a new WorkflowsIdTransferPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowsIdTransferPutRequestWithDefaults() *WorkflowsIdTransferPutRequest {
	this := WorkflowsIdTransferPutRequest{}
	return &this
}

// GetDestinationProjectId returns the DestinationProjectId field value
func (o *WorkflowsIdTransferPutRequest) GetDestinationProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DestinationProjectId
}

// GetDestinationProjectIdOk returns a tuple with the DestinationProjectId field value
// and a boolean to check if the value has been set.
func (o *WorkflowsIdTransferPutRequest) GetDestinationProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestinationProjectId, true
}

// SetDestinationProjectId sets field value
func (o *WorkflowsIdTransferPutRequest) SetDestinationProjectId(v string) {
	o.DestinationProjectId = v
}

func (o WorkflowsIdTransferPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowsIdTransferPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["destinationProjectId"] = o.DestinationProjectId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WorkflowsIdTransferPutRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"destinationProjectId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowsIdTransferPutRequest := _WorkflowsIdTransferPutRequest{}

	err = json.Unmarshal(data, &varWorkflowsIdTransferPutRequest)

	if err != nil {
		return err
	}

	*o = WorkflowsIdTransferPutRequest(varWorkflowsIdTransferPutRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "destinationProjectId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWorkflowsIdTransferPutRequest struct {
	value *WorkflowsIdTransferPutRequest
	isSet bool
}

func (v NullableWorkflowsIdTransferPutRequest) Get() *WorkflowsIdTransferPutRequest {
	return v.value
}

func (v *NullableWorkflowsIdTransferPutRequest) Set(val *WorkflowsIdTransferPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowsIdTransferPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowsIdTransferPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowsIdTransferPutRequest(val *WorkflowsIdTransferPutRequest) *NullableWorkflowsIdTransferPutRequest {
	return &NullableWorkflowsIdTransferPutRequest{value: val, isSet: true}
}

func (v NullableWorkflowsIdTransferPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowsIdTransferPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
