/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
)

// checks if the UsersPost200ResponseUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersPost200ResponseUser{}

// UsersPost200ResponseUser struct for UsersPost200ResponseUser
type UsersPost200ResponseUser struct {
	Id                   *string `json:"id,omitempty"`
	Email                *string `json:"email,omitempty"`
	InviteAcceptUrl      *string `json:"inviteAcceptUrl,omitempty"`
	EmailSent            *bool   `json:"emailSent,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UsersPost200ResponseUser UsersPost200ResponseUser

// NewUsersPost200ResponseUser instantiates a new UsersPost200ResponseUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersPost200ResponseUser() *UsersPost200ResponseUser {
	this := UsersPost200ResponseUser{}
	return &this
}

// NewUsersPost200ResponseUserWithDefaults instantiates a new UsersPost200ResponseUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersPost200ResponseUserWithDefaults() *UsersPost200ResponseUser {
	this := UsersPost200ResponseUser{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UsersPost200ResponseUser) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersPost200ResponseUser) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UsersPost200ResponseUser) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UsersPost200ResponseUser) SetId(v string) {
	o.Id = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *UsersPost200ResponseUser) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersPost200ResponseUser) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *UsersPost200ResponseUser) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *UsersPost200ResponseUser) SetEmail(v string) {
	o.Email = &v
}

// GetInviteAcceptUrl returns the InviteAcceptUrl field value if set, zero value otherwise.
func (o *UsersPost200ResponseUser) GetInviteAcceptUrl() string {
	if o == nil || IsNil(o.InviteAcceptUrl) {
		var ret string
		return ret
	}
	return *o.InviteAcceptUrl
}

// GetInviteAcceptUrlOk returns a tuple with the InviteAcceptUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersPost200ResponseUser) GetInviteAcceptUrlOk() (*string, bool) {
	if o == nil || IsNil(o.InviteAcceptUrl) {
		return nil, false
	}
	return o.InviteAcceptUrl, true
}

// HasInviteAcceptUrl returns a boolean if a field has been set.
func (o *UsersPost200ResponseUser) HasInviteAcceptUrl() bool {
	if o != nil && !IsNil(o.InviteAcceptUrl) {
		return true
	}

	return false
}

// SetInviteAcceptUrl gets a reference to the given string and assigns it to the InviteAcceptUrl field.
func (o *UsersPost200ResponseUser) SetInviteAcceptUrl(v string) {
	o.InviteAcceptUrl = &v
}

// GetEmailSent returns the EmailSent field value if set, zero value otherwise.
func (o *UsersPost200ResponseUser) GetEmailSent() bool {
	if o == nil || IsNil(o.EmailSent) {
		var ret bool
		return ret
	}
	return *o.EmailSent
}

// GetEmailSentOk returns a tuple with the EmailSent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersPost200ResponseUser) GetEmailSentOk() (*bool, bool) {
	if o == nil || IsNil(o.EmailSent) {
		return nil, false
	}
	return o.EmailSent, true
}

// HasEmailSent returns a boolean if a field has been set.
func (o *UsersPost200ResponseUser) HasEmailSent() bool {
	if o != nil && !IsNil(o.EmailSent) {
		return true
	}

	return false
}

// SetEmailSent gets a reference to the given bool and assigns it to the EmailSent field.
func (o *UsersPost200ResponseUser) SetEmailSent(v bool) {
	o.EmailSent = &v
}

func (o UsersPost200ResponseUser) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersPost200ResponseUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.InviteAcceptUrl) {
		toSerialize["inviteAcceptUrl"] = o.InviteAcceptUrl
	}
	if !IsNil(o.EmailSent) {
		toSerialize["emailSent"] = o.EmailSent
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UsersPost200ResponseUser) UnmarshalJSON(data []byte) (err error) {
	varUsersPost200ResponseUser := _UsersPost200ResponseUser{}

	err = json.Unmarshal(data, &varUsersPost200ResponseUser)

	if err != nil {
		return err
	}

	*o = UsersPost200ResponseUser(varUsersPost200ResponseUser)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "email")
		delete(additionalProperties, "inviteAcceptUrl")
		delete(additionalProperties, "emailSent")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUsersPost200ResponseUser struct {
	value *UsersPost200ResponseUser
	isSet bool
}

func (v NullableUsersPost200ResponseUser) Get() *UsersPost200ResponseUser {
	return v.value
}

func (v *NullableUsersPost200ResponseUser) Set(val *UsersPost200ResponseUser) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersPost200ResponseUser) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersPost200ResponseUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersPost200ResponseUser(val *UsersPost200ResponseUser) *NullableUsersPost200ResponseUser {
	return &NullableUsersPost200ResponseUser{value: val, isSet: true}
}

func (v NullableUsersPost200ResponseUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersPost200ResponseUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
