/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
	"time"
)

// checks if the Node type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Node{}

// Node struct for Node
type Node struct {
	Id               *string  `json:"id,omitempty"`
	Name             *string  `json:"name,omitempty"`
	WebhookId        *string  `json:"webhookId,omitempty"`
	Disabled         *bool    `json:"disabled,omitempty"`
	NotesInFlow      *bool    `json:"notesInFlow,omitempty"`
	Notes            *string  `json:"notes,omitempty"`
	Type             *string  `json:"type,omitempty"`
	TypeVersion      *float32 `json:"typeVersion,omitempty"`
	ExecuteOnce      *bool    `json:"executeOnce,omitempty"`
	AlwaysOutputData *bool    `json:"alwaysOutputData,omitempty"`
	RetryOnFail      *bool    `json:"retryOnFail,omitempty"`
	MaxTries         *float32 `json:"maxTries,omitempty"`
	WaitBetweenTries *float32 `json:"waitBetweenTries,omitempty"`
	// use onError instead
	// Deprecated
	ContinueOnFail *bool                  `json:"continueOnFail,omitempty"`
	OnError        *string                `json:"onError,omitempty"`
	Position       []float32              `json:"position,omitempty"`
	Parameters     map[string]interface{} `json:"parameters,omitempty"`
	Credentials    map[string]interface{} `json:"credentials,omitempty"`
	CreatedAt      *time.Time             `json:"createdAt,omitempty"`
	UpdatedAt      *time.Time             `json:"updatedAt,omitempty"`
}

// NewNode instantiates a new Node object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNode() *Node {
	this := Node{}
	return &this
}

// NewNodeWithDefaults instantiates a new Node object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodeWithDefaults() *Node {
	this := Node{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Node) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Node) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Node) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Node) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Node) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Node) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Node) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Node) SetName(v string) {
	o.Name = &v
}

// GetWebhookId returns the WebhookId field value if set, zero value otherwise.
func (o *Node) GetWebhookId() string {
	if o == nil || IsNil(o.WebhookId) {
		var ret string
		return ret
	}
	return *o.WebhookId
}

// GetWebhookIdOk returns a tuple with the WebhookId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Node) GetWebhookIdOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookId) {
		return nil, false
	}
	return o.WebhookId, true
}

// HasWebhookId returns a boolean if a field has been set.
func (o *Node) HasWebhookId() bool {
	if o != nil && !IsNil(o.WebhookId) {
		return true
	}

	return false
}

// SetWebhookId gets a reference to the given string and assigns it to the WebhookId field.
func (o *Node) SetWebhookId(v string) {
	o.WebhookId = &v
}

// GetDisabled returns the Disabled field value if set, zero value otherwise.
func (o *Node) GetDisabled() bool {
	if o == nil || IsNil(o.Disabled) {
		var ret bool
		return ret
	}
	return *o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Node) GetDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Disabled) {
		return nil, false
	}
	return o.Disabled, true
}

// HasDisabled returns a boolean if a field has been set.
func (o *Node) HasDisabled() bool {
	if o != nil && !IsNil(o.Disabled) {
		return true
	}

	return false
}

// SetDisabled gets a reference to the given bool and assigns it to the Disabled field.
func (o *Node) SetDisabled(v bool) {
	o.Disabled = &v
}

// GetNotesInFlow returns the NotesInFlow field value if set, zero value otherwise.
func (o *Node) GetNotesInFlow() bool {
	if o == nil || IsNil(o.NotesInFlow) {
		var ret bool
		return ret
	}
	return *o.NotesInFlow
}

// GetNotesInFlowOk returns a tuple with the NotesInFlow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Node) GetNotesInFlowOk() (*bool, bool) {
	if o == nil || IsNil(o.NotesInFlow) {
		return nil, false
	}
	return o.NotesInFlow, true
}

// HasNotesInFlow returns a boolean if a field has been set.
func (o *Node) HasNotesInFlow() bool {
	if o != nil && !IsNil(o.NotesInFlow) {
		return true
	}

	return false
}

// SetNotesInFlow gets a reference to the given bool and assigns it to the NotesInFlow field.
func (o *Node) SetNotesInFlow(v bool) {
	o.NotesInFlow = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *Node) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Node) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *Node) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *Node) SetNotes(v string) {
	o.Notes = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Node) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Node) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Node) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Node) SetType(v string) {
	o.Type = &v
}

// GetTypeVersion returns the TypeVersion field value if set, zero value otherwise.
func (o *Node) GetTypeVersion() float32 {
	if o == nil || IsNil(o.TypeVersion) {
		var ret float32
		return ret
	}
	return *o.TypeVersion
}

// GetTypeVersionOk returns a tuple with the TypeVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Node) GetTypeVersionOk() (*float32, bool) {
	if o == nil || IsNil(o.TypeVersion) {
		return nil, false
	}
	return o.TypeVersion, true
}

// HasTypeVersion returns a boolean if a field has been set.
func (o *Node) HasTypeVersion() bool {
	if o != nil && !IsNil(o.TypeVersion) {
		return true
	}

	return false
}

// SetTypeVersion gets a reference to the given float32 and assigns it to the TypeVersion field.
func (o *Node) SetTypeVersion(v float32) {
	o.TypeVersion = &v
}

// GetExecuteOnce returns the ExecuteOnce field value if set, zero value otherwise.
func (o *Node) GetExecuteOnce() bool {
	if o == nil || IsNil(o.ExecuteOnce) {
		var ret bool
		return ret
	}
	return *o.ExecuteOnce
}

// GetExecuteOnceOk returns a tuple with the ExecuteOnce field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Node) GetExecuteOnceOk() (*bool, bool) {
	if o == nil || IsNil(o.ExecuteOnce) {
		return nil, false
	}
	return o.ExecuteOnce, true
}

// HasExecuteOnce returns a boolean if a field has been set.
func (o *Node) HasExecuteOnce() bool {
	if o != nil && !IsNil(o.ExecuteOnce) {
		return true
	}

	return false
}

// SetExecuteOnce gets a reference to the given bool and assigns it to the ExecuteOnce field.
func (o *Node) SetExecuteOnce(v bool) {
	o.ExecuteOnce = &v
}

// GetAlwaysOutputData returns the AlwaysOutputData field value if set, zero value otherwise.
func (o *Node) GetAlwaysOutputData() bool {
	if o == nil || IsNil(o.AlwaysOutputData) {
		var ret bool
		return ret
	}
	return *o.AlwaysOutputData
}

// GetAlwaysOutputDataOk returns a tuple with the AlwaysOutputData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Node) GetAlwaysOutputDataOk() (*bool, bool) {
	if o == nil || IsNil(o.AlwaysOutputData) {
		return nil, false
	}
	return o.AlwaysOutputData, true
}

// HasAlwaysOutputData returns a boolean if a field has been set.
func (o *Node) HasAlwaysOutputData() bool {
	if o != nil && !IsNil(o.AlwaysOutputData) {
		return true
	}

	return false
}

// SetAlwaysOutputData gets a reference to the given bool and assigns it to the AlwaysOutputData field.
func (o *Node) SetAlwaysOutputData(v bool) {
	o.AlwaysOutputData = &v
}

// GetRetryOnFail returns the RetryOnFail field value if set, zero value otherwise.
func (o *Node) GetRetryOnFail() bool {
	if o == nil || IsNil(o.RetryOnFail) {
		var ret bool
		return ret
	}
	return *o.RetryOnFail
}

// GetRetryOnFailOk returns a tuple with the RetryOnFail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Node) GetRetryOnFailOk() (*bool, bool) {
	if o == nil || IsNil(o.RetryOnFail) {
		return nil, false
	}
	return o.RetryOnFail, true
}

// HasRetryOnFail returns a boolean if a field has been set.
func (o *Node) HasRetryOnFail() bool {
	if o != nil && !IsNil(o.RetryOnFail) {
		return true
	}

	return false
}

// SetRetryOnFail gets a reference to the given bool and assigns it to the RetryOnFail field.
func (o *Node) SetRetryOnFail(v bool) {
	o.RetryOnFail = &v
}

// GetMaxTries returns the MaxTries field value if set, zero value otherwise.
func (o *Node) GetMaxTries() float32 {
	if o == nil || IsNil(o.MaxTries) {
		var ret float32
		return ret
	}
	return *o.MaxTries
}

// GetMaxTriesOk returns a tuple with the MaxTries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Node) GetMaxTriesOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxTries) {
		return nil, false
	}
	return o.MaxTries, true
}

// HasMaxTries returns a boolean if a field has been set.
func (o *Node) HasMaxTries() bool {
	if o != nil && !IsNil(o.MaxTries) {
		return true
	}

	return false
}

// SetMaxTries gets a reference to the given float32 and assigns it to the MaxTries field.
func (o *Node) SetMaxTries(v float32) {
	o.MaxTries = &v
}

// GetWaitBetweenTries returns the WaitBetweenTries field value if set, zero value otherwise.
func (o *Node) GetWaitBetweenTries() float32 {
	if o == nil || IsNil(o.WaitBetweenTries) {
		var ret float32
		return ret
	}
	return *o.WaitBetweenTries
}

// GetWaitBetweenTriesOk returns a tuple with the WaitBetweenTries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Node) GetWaitBetweenTriesOk() (*float32, bool) {
	if o == nil || IsNil(o.WaitBetweenTries) {
		return nil, false
	}
	return o.WaitBetweenTries, true
}

// HasWaitBetweenTries returns a boolean if a field has been set.
func (o *Node) HasWaitBetweenTries() bool {
	if o != nil && !IsNil(o.WaitBetweenTries) {
		return true
	}

	return false
}

// SetWaitBetweenTries gets a reference to the given float32 and assigns it to the WaitBetweenTries field.
func (o *Node) SetWaitBetweenTries(v float32) {
	o.WaitBetweenTries = &v
}

// GetContinueOnFail returns the ContinueOnFail field value if set, zero value otherwise.
// Deprecated
func (o *Node) GetContinueOnFail() bool {
	if o == nil || IsNil(o.ContinueOnFail) {
		var ret bool
		return ret
	}
	return *o.ContinueOnFail
}

// GetContinueOnFailOk returns a tuple with the ContinueOnFail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *Node) GetContinueOnFailOk() (*bool, bool) {
	if o == nil || IsNil(o.ContinueOnFail) {
		return nil, false
	}
	return o.ContinueOnFail, true
}

// HasContinueOnFail returns a boolean if a field has been set.
func (o *Node) HasContinueOnFail() bool {
	if o != nil && !IsNil(o.ContinueOnFail) {
		return true
	}

	return false
}

// SetContinueOnFail gets a reference to the given bool and assigns it to the ContinueOnFail field.
// Deprecated
func (o *Node) SetContinueOnFail(v bool) {
	o.ContinueOnFail = &v
}

// GetOnError returns the OnError field value if set, zero value otherwise.
func (o *Node) GetOnError() string {
	if o == nil || IsNil(o.OnError) {
		var ret string
		return ret
	}
	return *o.OnError
}

// GetOnErrorOk returns a tuple with the OnError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Node) GetOnErrorOk() (*string, bool) {
	if o == nil || IsNil(o.OnError) {
		return nil, false
	}
	return o.OnError, true
}

// HasOnError returns a boolean if a field has been set.
func (o *Node) HasOnError() bool {
	if o != nil && !IsNil(o.OnError) {
		return true
	}

	return false
}

// SetOnError gets a reference to the given string and assigns it to the OnError field.
func (o *Node) SetOnError(v string) {
	o.OnError = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *Node) GetPosition() []float32 {
	if o == nil || IsNil(o.Position) {
		var ret []float32
		return ret
	}
	return o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Node) GetPositionOk() ([]float32, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *Node) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given []float32 and assigns it to the Position field.
func (o *Node) SetPosition(v []float32) {
	o.Position = v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *Node) GetParameters() map[string]interface{} {
	if o == nil || IsNil(o.Parameters) {
		var ret map[string]interface{}
		return ret
	}
	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Node) GetParametersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Parameters) {
		return map[string]interface{}{}, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *Node) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given map[string]interface{} and assigns it to the Parameters field.
func (o *Node) SetParameters(v map[string]interface{}) {
	o.Parameters = v
}

// GetCredentials returns the Credentials field value if set, zero value otherwise.
func (o *Node) GetCredentials() map[string]interface{} {
	if o == nil || IsNil(o.Credentials) {
		var ret map[string]interface{}
		return ret
	}
	return o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Node) GetCredentialsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Credentials) {
		return map[string]interface{}{}, false
	}
	return o.Credentials, true
}

// HasCredentials returns a boolean if a field has been set.
func (o *Node) HasCredentials() bool {
	if o != nil && !IsNil(o.Credentials) {
		return true
	}

	return false
}

// SetCredentials gets a reference to the given map[string]interface{} and assigns it to the Credentials field.
func (o *Node) SetCredentials(v map[string]interface{}) {
	o.Credentials = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Node) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Node) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Node) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Node) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Node) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Node) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Node) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Node) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o Node) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Node) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.WebhookId) {
		toSerialize["webhookId"] = o.WebhookId
	}
	if !IsNil(o.Disabled) {
		toSerialize["disabled"] = o.Disabled
	}
	if !IsNil(o.NotesInFlow) {
		toSerialize["notesInFlow"] = o.NotesInFlow
	}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.TypeVersion) {
		toSerialize["typeVersion"] = o.TypeVersion
	}
	if !IsNil(o.ExecuteOnce) {
		toSerialize["executeOnce"] = o.ExecuteOnce
	}
	if !IsNil(o.AlwaysOutputData) {
		toSerialize["alwaysOutputData"] = o.AlwaysOutputData
	}
	if !IsNil(o.RetryOnFail) {
		toSerialize["retryOnFail"] = o.RetryOnFail
	}
	if !IsNil(o.MaxTries) {
		toSerialize["maxTries"] = o.MaxTries
	}
	if !IsNil(o.WaitBetweenTries) {
		toSerialize["waitBetweenTries"] = o.WaitBetweenTries
	}
	if !IsNil(o.ContinueOnFail) {
		toSerialize["continueOnFail"] = o.ContinueOnFail
	}
	if !IsNil(o.OnError) {
		toSerialize["onError"] = o.OnError
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}
	if !IsNil(o.Credentials) {
		toSerialize["credentials"] = o.Credentials
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableNode struct {
	value *Node
	isSet bool
}

func (v NullableNode) Get() *Node {
	return v.value
}

func (v *NullableNode) Set(val *Node) {
	v.value = val
	v.isSet = true
}

func (v NullableNode) IsSet() bool {
	return v.isSet
}

func (v *NullableNode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNode(val *Node) *NullableNode {
	return &NullableNode{value: val, isSet: true}
}

func (v NullableNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
