/*
n8n Public API

n8n Public API

API version: 1.1.1
Contact: hello@n8n.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package n8nsdk

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// UpsertDataTableRow200Response - struct for UpsertDataTableRow200Response
type UpsertDataTableRow200Response struct {
	DataTableRow *DataTableRow
	Bool         *bool
}

// DataTableRowAsUpsertDataTableRow200Response is a convenience function that returns DataTableRow wrapped in UpsertDataTableRow200Response
func DataTableRowAsUpsertDataTableRow200Response(v *DataTableRow) UpsertDataTableRow200Response {
	return UpsertDataTableRow200Response{
		DataTableRow: v,
	}
}

// boolAsUpsertDataTableRow200Response is a convenience function that returns bool wrapped in UpsertDataTableRow200Response
func BoolAsUpsertDataTableRow200Response(v *bool) UpsertDataTableRow200Response {
	return UpsertDataTableRow200Response{
		Bool: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *UpsertDataTableRow200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into DataTableRow
	err = newStrictDecoder(data).Decode(&dst.DataTableRow)
	if err == nil {
		jsonDataTableRow, _ := json.Marshal(dst.DataTableRow)
		if string(jsonDataTableRow) == "{}" { // empty struct
			dst.DataTableRow = nil
		} else {
			if err = validator.Validate(dst.DataTableRow); err != nil {
				dst.DataTableRow = nil
			} else {
				match++
			}
		}
	} else {
		dst.DataTableRow = nil
	}

	// try to unmarshal data into Bool
	err = newStrictDecoder(data).Decode(&dst.Bool)
	if err == nil {
		jsonBool, _ := json.Marshal(dst.Bool)
		if string(jsonBool) == "{}" { // empty struct
			dst.Bool = nil
		} else {
			if err = validator.Validate(dst.Bool); err != nil {
				dst.Bool = nil
			} else {
				match++
			}
		}
	} else {
		dst.Bool = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.DataTableRow = nil
		dst.Bool = nil

		return fmt.Errorf("data matches more than one schema in oneOf(UpsertDataTableRow200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(UpsertDataTableRow200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src UpsertDataTableRow200Response) MarshalJSON() ([]byte, error) {
	if src.DataTableRow != nil {
		return json.Marshal(&src.DataTableRow)
	}

	if src.Bool != nil {
		return json.Marshal(&src.Bool)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *UpsertDataTableRow200Response) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.DataTableRow != nil {
		return obj.DataTableRow
	}

	if obj.Bool != nil {
		return obj.Bool
	}

	// all schemas are nil
	return nil
}

type NullableUpsertDataTableRow200Response struct {
	value *UpsertDataTableRow200Response
	isSet bool
}

func (v NullableUpsertDataTableRow200Response) Get() *UpsertDataTableRow200Response {
	return v.value
}

func (v *NullableUpsertDataTableRow200Response) Set(val *UpsertDataTableRow200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpsertDataTableRow200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpsertDataTableRow200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpsertDataTableRow200Response(val *UpsertDataTableRow200Response) *NullableUpsertDataTableRow200Response {
	return &NullableUpsertDataTableRow200Response{value: val, isSet: true}
}

func (v NullableUpsertDataTableRow200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpsertDataTableRow200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
